TARGETNAME=winmine
TARGETPATH=../../bin
TARGETTYPE=APPLICATION
CC = /usr/local/armv7-pc-mingw32/bin/clang
CXX = /usr/local/armv7-pc-mingw32/bin/clang+
AR = /usr/local/armv7-pc-mingw32/bin/llvm-ar
WINDRES = /usr/local/armv7-pc-mingw32/bin/llvm-windres -D_UNICODE=1 -DUNICODE=1
RANLIB = /usr/local/armv7-pc-mingw32/bin/llvm-ranlib
CFLAGS = -O2 -I. -Wall -D_UNICODE=1 -DUNICODE=1
LDFLAGS = -mwindows
LIBS = -lgdi32 -lhtmlhelp -lwinmm -lcomctl32
RM = rm -f
INSTALL = install -m 755
INSTALL_DIR = /usr

OBJS = \
	grafix.o \
	pref.o \
	rtns.o \
	sound.o \
	util.o \
	winmine.o \
	res.o

%.o: %.rc
	$(WINDRES) -o $@ $<

%.o: %.c
	$(CC) $(CFLAGS) -DLIB_EXPORTS=1 -o $@ -c $<

all: $(TARGETNAME).exe

$(TARGETNAME).exe: $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	$(RM) $(OBJS) $(DLL_OBJS) $(TARGETNAME).exe

install:
	$(INSTALL) $(TARGETNAME).exe $(INSTALL_DIR)/bin/$(TARGETNAME).exe

