/* strings.inc */

STRINGTABLE
  BEGIN
    idsHelpFile,     TEXT("winmine.chm")
    idsNoHelp,       TEXT("Unable load Windows Help application")
    idsHelpIndex,    TEXT("Index of Mine Sweeper help topics")
    idsHelpSearch,   TEXT("Search the Help Engine for a specific topic")
    idsHelpUsing,    TEXT("Help using help")
    ID_GAMENAME      TEXT("Minesweeper")
    ID_ERR_TITLE     TEXT("Minesweeper Error")
    ID_ERR_TIMER,    TEXT("Unable to allocate a timer.  Please exit some of your applications and try again.")
    ID_ERR_UNKNOWN,  TEXT("Error: %d")
    ID_ERR_MEM,      TEXT("Out of Memory")
    ID_NAME_DEFAULT, TEXT("Anonymous")
    ID_MSG_SEC,      TEXT("%d seconds")
    ID_MSG_BEGIN,    TEXT("You have the fastest time\rfor beginner level.\rPlease enter your name.")
    ID_MSG_INTER,    TEXT("You have the fastest time\rfor intermediate level.\rPlease enter your name.")
    ID_MSG_EXPERT,   TEXT("You have the fastest time\rfor expert level.\rPlease enter your name.")
    ID_MSG_VERSION,  TEXT("Minesweeper")
    ID_MSG_CREDIT,   TEXT("by Robert Donner and Curt Johnson")
  END

