//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this source code is subject to the terms of the Microsoft end-user
// license agreement (EULA) under which you licensed this SOFTWARE PRODUCT.
// If you did not accept the terms of the EULA, you are not authorized to use
// this source code. For a copy of the EULA, please see the LICENSE.RTF on your
// install media.
//
#include <olectl.h>
// atl.idl : IDL source for atl.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (atl.tlb) and marshalling code.
import "oaidl.idl";
import "atliface.idl";
import  "ocidl.idl";

[
	uuid(44EC0535-400F-11D0-9DCD-00A0C90391D3),
	version(1.0),
	helpstring("ATL 2.0 Type Library")
]
library ATLLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	interface IAxWinAmbientDispatch;
#if !defined(_WIN32_WCE)
	interface IDocHostUIHandlerDispatch;
#endif // !_WIN32_WCE
};
