/*** Autogenerated by WIDL 10.10 from ../../include/atliface.idl - Do not edit ***/

#define __midl_proxy
#include "objbase.h"

#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 475
#endif

#define USE_STUBLESS_PROXY
#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error This code needs a newer version of rpcproxy.h
#endif /* __RPCPROXY_H_VERSION__ */

#include "atliface.h"

#define TYPE_FORMAT_STRING_SIZE 675
#define PROC_FORMAT_STRING_SIZE 2393

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const MIDL_STUB_DESC Object_StubDesc;

/*****************************************************************************
 * IRegistrarBase interface
 */
static const unsigned short IRegistrarBase_FormatStringOffsetTable[] =
{
    0,  /* IRegistrarBase::AddReplacement */
    48,  /* IRegistrarBase::ClearReplacements */
};

static const MIDL_STUBLESS_PROXY_INFO IRegistrarBase_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IRegistrarBase_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(5) _IRegistrarBaseProxyVtbl =
{
    {
        &IRegistrarBase_ProxyInfo,
        &IID_IRegistrarBase,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IRegistrarBase::AddReplacement */
        (void *)-1,  /* IRegistrarBase::ClearReplacements */
    }
};

static const MIDL_SERVER_INFO IRegistrarBase_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IRegistrarBase_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IRegistrarBaseStubVtbl =
{
    {
        &IID_IRegistrarBase,
        &IRegistrarBase_ServerInfo,
        5,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IRegistrar interface
 */
static const unsigned short IRegistrar_FormatStringOffsetTable[] =
{
    0,  /* IRegistrarBase::AddReplacement */
    48,  /* IRegistrarBase::ClearReplacements */
    82,  /* IRegistrar::ResourceRegisterSz */
    138,  /* IRegistrar::ResourceUnregisterSz */
    194,  /* IRegistrar::FileRegister */
    236,  /* IRegistrar::FileUnregister */
    278,  /* IRegistrar::StringRegister */
    320,  /* IRegistrar::StringUnregister */
    362,  /* IRegistrar::ResourceRegister */
    418,  /* IRegistrar::ResourceUnregister */
};

static const MIDL_STUBLESS_PROXY_INFO IRegistrar_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IRegistrar_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(13) _IRegistrarProxyVtbl =
{
    {
        &IRegistrar_ProxyInfo,
        &IID_IRegistrar,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IRegistrarBase::AddReplacement */
        (void *)-1,  /* IRegistrarBase::ClearReplacements */
        (void *)-1,  /* IRegistrar::ResourceRegisterSz */
        (void *)-1,  /* IRegistrar::ResourceUnregisterSz */
        (void *)-1,  /* IRegistrar::FileRegister */
        (void *)-1,  /* IRegistrar::FileUnregister */
        (void *)-1,  /* IRegistrar::StringRegister */
        (void *)-1,  /* IRegistrar::StringUnregister */
        (void *)-1,  /* IRegistrar::ResourceRegister */
        (void *)-1,  /* IRegistrar::ResourceUnregister */
    }
};

static const MIDL_SERVER_INFO IRegistrar_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IRegistrar_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IRegistrarStubVtbl =
{
    {
        &IID_IRegistrar,
        &IRegistrar_ServerInfo,
        13,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IAxWinHostWindow interface
 */
static const unsigned short IAxWinHostWindow_FormatStringOffsetTable[] =
{
    474,  /* IAxWinHostWindow::CreateControl */
    530,  /* IAxWinHostWindow::CreateControlEx */
    606,  /* IAxWinHostWindow::AttachControl */
    654,  /* IAxWinHostWindow::QueryControl */
    702,  /* IAxWinHostWindow::SetExternalDispatch */
    744,  /* IAxWinHostWindow::SetExternalUIHandler */
};

static const MIDL_STUBLESS_PROXY_INFO IAxWinHostWindow_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IAxWinHostWindow_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(9) _IAxWinHostWindowProxyVtbl =
{
    {
        &IAxWinHostWindow_ProxyInfo,
        &IID_IAxWinHostWindow,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IAxWinHostWindow::CreateControl */
        (void *)-1,  /* IAxWinHostWindow::CreateControlEx */
        (void *)-1,  /* IAxWinHostWindow::AttachControl */
        (void *)-1,  /* IAxWinHostWindow::QueryControl */
        (void *)-1,  /* IAxWinHostWindow::SetExternalDispatch */
        (void *)-1,  /* IAxWinHostWindow::SetExternalUIHandler */
    }
};

static const MIDL_SERVER_INFO IAxWinHostWindow_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IAxWinHostWindow_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IAxWinHostWindowStubVtbl =
{
    {
        &IID_IAxWinHostWindow,
        &IAxWinHostWindow_ServerInfo,
        9,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IAxWinHostWindowLic interface
 */
static const unsigned short IAxWinHostWindowLic_FormatStringOffsetTable[] =
{
    474,  /* IAxWinHostWindow::CreateControl */
    530,  /* IAxWinHostWindow::CreateControlEx */
    606,  /* IAxWinHostWindow::AttachControl */
    654,  /* IAxWinHostWindow::QueryControl */
    702,  /* IAxWinHostWindow::SetExternalDispatch */
    744,  /* IAxWinHostWindow::SetExternalUIHandler */
    786,  /* IAxWinHostWindowLic::CreateControlLic */
    848,  /* IAxWinHostWindowLic::CreateControlLicEx */
};

static const MIDL_STUBLESS_PROXY_INFO IAxWinHostWindowLic_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IAxWinHostWindowLic_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(11) _IAxWinHostWindowLicProxyVtbl =
{
    {
        &IAxWinHostWindowLic_ProxyInfo,
        &IID_IAxWinHostWindowLic,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IAxWinHostWindow::CreateControl */
        (void *)-1,  /* IAxWinHostWindow::CreateControlEx */
        (void *)-1,  /* IAxWinHostWindow::AttachControl */
        (void *)-1,  /* IAxWinHostWindow::QueryControl */
        (void *)-1,  /* IAxWinHostWindow::SetExternalDispatch */
        (void *)-1,  /* IAxWinHostWindow::SetExternalUIHandler */
        (void *)-1,  /* IAxWinHostWindowLic::CreateControlLic */
        (void *)-1,  /* IAxWinHostWindowLic::CreateControlLicEx */
    }
};

static const MIDL_SERVER_INFO IAxWinHostWindowLic_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IAxWinHostWindowLic_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IAxWinHostWindowLicStubVtbl =
{
    {
        &IID_IAxWinHostWindowLic,
        &IAxWinHostWindowLic_ServerInfo,
        11,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IAxWinAmbientDispatch interface
 */
static const unsigned short IAxWinAmbientDispatch_FormatStringOffsetTable[] =
{
    (unsigned short)-1,  /* IDispatch::GetTypeInfoCount */
    (unsigned short)-1,  /* IDispatch::GetTypeInfo */
    (unsigned short)-1,  /* IDispatch::GetIDsOfNames */
    (unsigned short)-1,  /* IDispatch::RemoteInvoke */
    932,  /* IAxWinAmbientDispatch::put_AllowWindowlessActivation */
    974,  /* IAxWinAmbientDispatch::get_AllowWindowlessActivation */
    1016,  /* IAxWinAmbientDispatch::put_BackColor */
    1058,  /* IAxWinAmbientDispatch::get_BackColor */
    1100,  /* IAxWinAmbientDispatch::put_ForeColor */
    1142,  /* IAxWinAmbientDispatch::get_ForeColor */
    1184,  /* IAxWinAmbientDispatch::put_LocaleID */
    1226,  /* IAxWinAmbientDispatch::get_LocaleID */
    1268,  /* IAxWinAmbientDispatch::put_UserMode */
    1310,  /* IAxWinAmbientDispatch::get_UserMode */
    1352,  /* IAxWinAmbientDispatch::put_DisplayAsDefault */
    1394,  /* IAxWinAmbientDispatch::get_DisplayAsDefault */
    1436,  /* IAxWinAmbientDispatch::put_Font */
    1478,  /* IAxWinAmbientDispatch::get_Font */
    1520,  /* IAxWinAmbientDispatch::put_MessageReflect */
    1562,  /* IAxWinAmbientDispatch::get_MessageReflect */
    1604,  /* IAxWinAmbientDispatch::get_ShowGrabHandles */
    1646,  /* IAxWinAmbientDispatch::get_ShowHatching */
    1688,  /* IAxWinAmbientDispatch::put_DocHostFlags */
    1730,  /* IAxWinAmbientDispatch::get_DocHostFlags */
    1772,  /* IAxWinAmbientDispatch::put_DocHostDoubleClickFlags */
    1814,  /* IAxWinAmbientDispatch::get_DocHostDoubleClickFlags */
    1856,  /* IAxWinAmbientDispatch::put_AllowContextMenu */
    1898,  /* IAxWinAmbientDispatch::get_AllowContextMenu */
    1940,  /* IAxWinAmbientDispatch::put_AllowShowUI */
    1982,  /* IAxWinAmbientDispatch::get_AllowShowUI */
    2024,  /* IAxWinAmbientDispatch::put_OptionKeyPath */
    2066,  /* IAxWinAmbientDispatch::get_OptionKeyPath */
};

static const MIDL_STUBLESS_PROXY_INFO IAxWinAmbientDispatch_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IAxWinAmbientDispatch_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(35) _IAxWinAmbientDispatchProxyVtbl =
{
    {
        &IAxWinAmbientDispatch_ProxyInfo,
        &IID_IAxWinAmbientDispatch,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        0,  /* IDispatch::GetTypeInfoCount */
        0,  /* IDispatch::GetTypeInfo */
        0,  /* IDispatch::GetIDsOfNames */
        0,  /* IDispatch::Invoke */
        (void *)-1,  /* IAxWinAmbientDispatch::put_AllowWindowlessActivation */
        (void *)-1,  /* IAxWinAmbientDispatch::get_AllowWindowlessActivation */
        (void *)-1,  /* IAxWinAmbientDispatch::put_BackColor */
        (void *)-1,  /* IAxWinAmbientDispatch::get_BackColor */
        (void *)-1,  /* IAxWinAmbientDispatch::put_ForeColor */
        (void *)-1,  /* IAxWinAmbientDispatch::get_ForeColor */
        (void *)-1,  /* IAxWinAmbientDispatch::put_LocaleID */
        (void *)-1,  /* IAxWinAmbientDispatch::get_LocaleID */
        (void *)-1,  /* IAxWinAmbientDispatch::put_UserMode */
        (void *)-1,  /* IAxWinAmbientDispatch::get_UserMode */
        (void *)-1,  /* IAxWinAmbientDispatch::put_DisplayAsDefault */
        (void *)-1,  /* IAxWinAmbientDispatch::get_DisplayAsDefault */
        (void *)-1,  /* IAxWinAmbientDispatch::put_Font */
        (void *)-1,  /* IAxWinAmbientDispatch::get_Font */
        (void *)-1,  /* IAxWinAmbientDispatch::put_MessageReflect */
        (void *)-1,  /* IAxWinAmbientDispatch::get_MessageReflect */
        (void *)-1,  /* IAxWinAmbientDispatch::get_ShowGrabHandles */
        (void *)-1,  /* IAxWinAmbientDispatch::get_ShowHatching */
        (void *)-1,  /* IAxWinAmbientDispatch::put_DocHostFlags */
        (void *)-1,  /* IAxWinAmbientDispatch::get_DocHostFlags */
        (void *)-1,  /* IAxWinAmbientDispatch::put_DocHostDoubleClickFlags */
        (void *)-1,  /* IAxWinAmbientDispatch::get_DocHostDoubleClickFlags */
        (void *)-1,  /* IAxWinAmbientDispatch::put_AllowContextMenu */
        (void *)-1,  /* IAxWinAmbientDispatch::get_AllowContextMenu */
        (void *)-1,  /* IAxWinAmbientDispatch::put_AllowShowUI */
        (void *)-1,  /* IAxWinAmbientDispatch::get_AllowShowUI */
        (void *)-1,  /* IAxWinAmbientDispatch::put_OptionKeyPath */
        (void *)-1,  /* IAxWinAmbientDispatch::get_OptionKeyPath */
    }
};

static const MIDL_SERVER_INFO IAxWinAmbientDispatch_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IAxWinAmbientDispatch_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const PRPC_STUB_FUNCTION IAxWinAmbientDispatch_table[] =
{
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2
};

static CInterfaceStubVtbl _IAxWinAmbientDispatchStubVtbl =
{
    {
        &IID_IAxWinAmbientDispatch,
        &IAxWinAmbientDispatch_ServerInfo,
        35,
        &IAxWinAmbientDispatch_table[-3]
    },
    {
        CStdStubBuffer_DELEGATING_METHODS
    }
};

/*****************************************************************************
 * IAxWinAmbientDispatchEx interface
 */
static const unsigned short IAxWinAmbientDispatchEx_FormatStringOffsetTable[] =
{
    (unsigned short)-1,  /* IDispatch::GetTypeInfoCount */
    (unsigned short)-1,  /* IDispatch::GetTypeInfo */
    (unsigned short)-1,  /* IDispatch::GetIDsOfNames */
    (unsigned short)-1,  /* IDispatch::RemoteInvoke */
    932,  /* IAxWinAmbientDispatch::put_AllowWindowlessActivation */
    974,  /* IAxWinAmbientDispatch::get_AllowWindowlessActivation */
    1016,  /* IAxWinAmbientDispatch::put_BackColor */
    1058,  /* IAxWinAmbientDispatch::get_BackColor */
    1100,  /* IAxWinAmbientDispatch::put_ForeColor */
    1142,  /* IAxWinAmbientDispatch::get_ForeColor */
    1184,  /* IAxWinAmbientDispatch::put_LocaleID */
    1226,  /* IAxWinAmbientDispatch::get_LocaleID */
    1268,  /* IAxWinAmbientDispatch::put_UserMode */
    1310,  /* IAxWinAmbientDispatch::get_UserMode */
    1352,  /* IAxWinAmbientDispatch::put_DisplayAsDefault */
    1394,  /* IAxWinAmbientDispatch::get_DisplayAsDefault */
    1436,  /* IAxWinAmbientDispatch::put_Font */
    1478,  /* IAxWinAmbientDispatch::get_Font */
    1520,  /* IAxWinAmbientDispatch::put_MessageReflect */
    1562,  /* IAxWinAmbientDispatch::get_MessageReflect */
    1604,  /* IAxWinAmbientDispatch::get_ShowGrabHandles */
    1646,  /* IAxWinAmbientDispatch::get_ShowHatching */
    1688,  /* IAxWinAmbientDispatch::put_DocHostFlags */
    1730,  /* IAxWinAmbientDispatch::get_DocHostFlags */
    1772,  /* IAxWinAmbientDispatch::put_DocHostDoubleClickFlags */
    1814,  /* IAxWinAmbientDispatch::get_DocHostDoubleClickFlags */
    1856,  /* IAxWinAmbientDispatch::put_AllowContextMenu */
    1898,  /* IAxWinAmbientDispatch::get_AllowContextMenu */
    1940,  /* IAxWinAmbientDispatch::put_AllowShowUI */
    1982,  /* IAxWinAmbientDispatch::get_AllowShowUI */
    2024,  /* IAxWinAmbientDispatch::put_OptionKeyPath */
    2066,  /* IAxWinAmbientDispatch::get_OptionKeyPath */
    2108,  /* IAxWinAmbientDispatchEx::SetAmbientDispatch */
};

static const MIDL_STUBLESS_PROXY_INFO IAxWinAmbientDispatchEx_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IAxWinAmbientDispatchEx_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(36) _IAxWinAmbientDispatchExProxyVtbl =
{
    {
        &IAxWinAmbientDispatchEx_ProxyInfo,
        &IID_IAxWinAmbientDispatchEx,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        0,  /* IDispatch::GetTypeInfoCount */
        0,  /* IDispatch::GetTypeInfo */
        0,  /* IDispatch::GetIDsOfNames */
        0,  /* IDispatch::Invoke */
        (void *)-1,  /* IAxWinAmbientDispatch::put_AllowWindowlessActivation */
        (void *)-1,  /* IAxWinAmbientDispatch::get_AllowWindowlessActivation */
        (void *)-1,  /* IAxWinAmbientDispatch::put_BackColor */
        (void *)-1,  /* IAxWinAmbientDispatch::get_BackColor */
        (void *)-1,  /* IAxWinAmbientDispatch::put_ForeColor */
        (void *)-1,  /* IAxWinAmbientDispatch::get_ForeColor */
        (void *)-1,  /* IAxWinAmbientDispatch::put_LocaleID */
        (void *)-1,  /* IAxWinAmbientDispatch::get_LocaleID */
        (void *)-1,  /* IAxWinAmbientDispatch::put_UserMode */
        (void *)-1,  /* IAxWinAmbientDispatch::get_UserMode */
        (void *)-1,  /* IAxWinAmbientDispatch::put_DisplayAsDefault */
        (void *)-1,  /* IAxWinAmbientDispatch::get_DisplayAsDefault */
        (void *)-1,  /* IAxWinAmbientDispatch::put_Font */
        (void *)-1,  /* IAxWinAmbientDispatch::get_Font */
        (void *)-1,  /* IAxWinAmbientDispatch::put_MessageReflect */
        (void *)-1,  /* IAxWinAmbientDispatch::get_MessageReflect */
        (void *)-1,  /* IAxWinAmbientDispatch::get_ShowGrabHandles */
        (void *)-1,  /* IAxWinAmbientDispatch::get_ShowHatching */
        (void *)-1,  /* IAxWinAmbientDispatch::put_DocHostFlags */
        (void *)-1,  /* IAxWinAmbientDispatch::get_DocHostFlags */
        (void *)-1,  /* IAxWinAmbientDispatch::put_DocHostDoubleClickFlags */
        (void *)-1,  /* IAxWinAmbientDispatch::get_DocHostDoubleClickFlags */
        (void *)-1,  /* IAxWinAmbientDispatch::put_AllowContextMenu */
        (void *)-1,  /* IAxWinAmbientDispatch::get_AllowContextMenu */
        (void *)-1,  /* IAxWinAmbientDispatch::put_AllowShowUI */
        (void *)-1,  /* IAxWinAmbientDispatch::get_AllowShowUI */
        (void *)-1,  /* IAxWinAmbientDispatch::put_OptionKeyPath */
        (void *)-1,  /* IAxWinAmbientDispatch::get_OptionKeyPath */
        (void *)-1,  /* IAxWinAmbientDispatchEx::SetAmbientDispatch */
    }
};

static const MIDL_SERVER_INFO IAxWinAmbientDispatchEx_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IAxWinAmbientDispatchEx_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static CInterfaceStubVtbl _IAxWinAmbientDispatchExStubVtbl =
{
    {
        &IID_IAxWinAmbientDispatchEx,
        &IAxWinAmbientDispatchEx_ServerInfo,
        36,
        0
    },
    {
        CStdStubBuffer_DELEGATING_METHODS
    }
};

/*****************************************************************************
 * IInternalConnection interface
 */
static const unsigned short IInternalConnection_FormatStringOffsetTable[] =
{
    2150,  /* IInternalConnection::AddConnection */
    2184,  /* IInternalConnection::ReleaseConnection */
};

static const MIDL_STUBLESS_PROXY_INFO IInternalConnection_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IInternalConnection_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(5) _IInternalConnectionProxyVtbl =
{
    {
        &IInternalConnection_ProxyInfo,
        &IID_IInternalConnection,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IInternalConnection::AddConnection */
        (void *)-1,  /* IInternalConnection::ReleaseConnection */
    }
};

static const MIDL_SERVER_INFO IInternalConnection_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IInternalConnection_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IInternalConnectionStubVtbl =
{
    {
        &IID_IInternalConnection,
        &IInternalConnection_ServerInfo,
        5,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IAccessibleProxy interface
 */
static const unsigned short IAccessibleProxy_FormatStringOffsetTable[] =
{
    2218,  /* IAccessibleProxy::SetServer */
};

static const MIDL_STUBLESS_PROXY_INFO IAccessibleProxy_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IAccessibleProxy_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(4) _IAccessibleProxyProxyVtbl =
{
    {
        &IAccessibleProxy_ProxyInfo,
        &IID_IAccessibleProxy,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IAccessibleProxy::SetServer */
    }
};

static const MIDL_SERVER_INFO IAccessibleProxy_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IAccessibleProxy_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IAccessibleProxyStubVtbl =
{
    {
        &IID_IAccessibleProxy,
        &IAccessibleProxy_ServerInfo,
        4,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IAccessibleServer interface
 */
static const unsigned short IAccessibleServer_FormatStringOffsetTable[] =
{
    2266,  /* IAccessibleServer::SetProxy */
    2308,  /* IAccessibleServer::GetHWND */
    2350,  /* IAccessibleServer::GetEnumVariant */
};

static const MIDL_STUBLESS_PROXY_INFO IAccessibleServer_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IAccessibleServer_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(6) _IAccessibleServerProxyVtbl =
{
    {
        &IAccessibleServer_ProxyInfo,
        &IID_IAccessibleServer,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IAccessibleServer::SetProxy */
        (void *)-1,  /* IAccessibleServer::GetHWND */
        (void *)-1,  /* IAccessibleServer::GetEnumVariant */
    }
};

static const MIDL_SERVER_INFO IAccessibleServer_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IAccessibleServer_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IAccessibleServerStubVtbl =
{
    {
        &IID_IAccessibleServer,
        &IAccessibleServer_ServerInfo,
        6,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

static const USER_MARSHAL_ROUTINE_QUADRUPLE UserMarshalRoutines[] =
{
    {
        (USER_MARSHAL_SIZING_ROUTINE)HWND_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)HWND_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)HWND_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)HWND_UserFree
    },
    {
        (USER_MARSHAL_SIZING_ROUTINE)BSTR_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)BSTR_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)BSTR_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)BSTR_UserFree
    }
};

static const MIDL_STUB_DESC Object_StubDesc =
{
    0,
    NdrOleAllocate,
    NdrOleFree,
    {0}, 0, 0, 0, 0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    UserMarshalRoutines,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

#if !defined(__RPC_WIN64__)
#error Invalid build platform for this proxy.
#endif

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure IRegistrarBase::AddReplacement) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x03),
        0x03,
        0x80,
        0x81,
        0x82,
/* 30 (parameter key) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x4),	/* type offset = 4 */
/* 36 (parameter item) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x8),	/* type offset = 8 */
/* 42 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 48 (procedure IRegistrarBase::ClearReplacements) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x0c,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x01),
        0x01,
        0x80,
/* 76 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 82 (procedure IRegistrar::ResourceRegisterSz) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x10,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x04),
        0x04,
        0x80,
        0x81,
        0x82,
        0x83,
        0x00,
/* 114 (parameter resFileName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xc),	/* type offset = 12 */
/* 120 (parameter szID) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x10),	/* type offset = 16 */
/* 126 (parameter szType) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 132 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 138 (procedure IRegistrar::ResourceUnregisterSz) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x10,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x04),
        0x04,
        0x80,
        0x81,
        0x82,
        0x83,
        0x00,
/* 170 (parameter resFileName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x18),	/* type offset = 24 */
/* 176 (parameter szID) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x1c),	/* type offset = 28 */
/* 182 (parameter szType) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x20),	/* type offset = 32 */
/* 188 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 194 (procedure IRegistrar::FileRegister) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 224 (parameter fileName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x24),	/* type offset = 36 */
/* 230 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 236 (procedure IRegistrar::FileUnregister) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 266 (parameter fileName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x28),	/* type offset = 40 */
/* 272 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 278 (procedure IRegistrar::StringRegister) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 308 (parameter data) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x2c),	/* type offset = 44 */
/* 314 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 320 (procedure IRegistrar::StringUnregister) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xa),	/* method 10 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 350 (parameter data) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x30),	/* type offset = 48 */
/* 356 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 362 (procedure IRegistrar::ResourceRegister) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xb),	/* method 11 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x10,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x04),
        0x04,
        0x80,
        0x81,
        0x82,
        0x83,
        0x00,
/* 394 (parameter resFileName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x34),	/* type offset = 52 */
/* 400 (parameter nID) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 406 (parameter szType) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x38),	/* type offset = 56 */
/* 412 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 418 (procedure IRegistrar::ResourceUnregister) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xc),	/* method 12 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x10,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x04),
        0x04,
        0x80,
        0x81,
        0x82,
        0x83,
        0x00,
/* 450 (parameter resFileName) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x3c),	/* type offset = 60 */
/* 456 (parameter nID) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 462 (parameter szType) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x40),	/* type offset = 64 */
/* 468 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 474 (procedure IAxWinHostWindow::CreateControl) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x10,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x04),
        0x04,
        0x80,
        0x81,
        0x82,
        0x83,
        0x00,
/* 506 (parameter lpTricsData) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x44),	/* type offset = 68 */
/* 512 (parameter hWnd) */
        NdrFcShort(0x8b),	/* flags: must size, must free, in, by value */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x5e),	/* type offset = 94 */
/* 518 (parameter pStream) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x68),	/* type offset = 104 */
/* 524 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 530 (procedure IAxWinHostWindow::CreateControlEx) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x40),	/* stack size = 64 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x07,	/* 7 params */
        0x12,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x07),
        0x07,
        0x80,
        0x81,
        0x82,
        0x83,
        0x84,
        0x85,
        0x86,
/* 564 (parameter lpTricsData) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x7c),	/* type offset = 124 */
/* 570 (parameter hWnd) */
        NdrFcShort(0x8b),	/* flags: must size, must free, in, by value */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x7e),	/* type offset = 126 */
/* 576 (parameter pStream) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x88),	/* type offset = 136 */
/* 582 (parameter ppUnk) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0xac),	/* type offset = 172 */
/* 588 (parameter riidAdvise) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0xb6),	/* type offset = 182 */
/* 594 (parameter punkAdvise) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0xc6),	/* type offset = 198 */
/* 600 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 606 (procedure IAxWinHostWindow::AttachControl) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x03),
        0x03,
        0x80,
        0x81,
        0x82,
/* 636 (parameter pUnkControl) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xd8),	/* type offset = 216 */
/* 642 (parameter hWnd) */
        NdrFcShort(0x8b),	/* flags: must size, must free, in, by value */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xea),	/* type offset = 234 */
/* 648 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 654 (procedure IAxWinHostWindow::QueryControl) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x03),
        0x03,
        0x80,
        0x81,
        0x82,
/* 684 (parameter riid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xb6),	/* type offset = 182 */
/* 690 (parameter ppvObject) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x100),	/* type offset = 256 */
/* 696 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 702 (procedure IAxWinHostWindow::SetExternalDispatch) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 732 (parameter pDisp) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x104),	/* type offset = 260 */
/* 738 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 744 (procedure IAxWinHostWindow::SetExternalUIHandler) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 774 (parameter pDisp) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x116),	/* type offset = 278 */
/* 780 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 786 (procedure IAxWinHostWindowLic::CreateControlLic) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0x30),	/* stack size = 48 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x05,	/* 5 params */
        0x10,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x05),
        0x05,
        0x80,
        0x81,
        0x82,
        0x83,
        0x84,
/* 818 (parameter lpTricsData) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x12a),	/* type offset = 298 */
/* 824 (parameter hWnd) */
        NdrFcShort(0x8b),	/* flags: must size, must free, in, by value */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x12c),	/* type offset = 300 */
/* 830 (parameter pStream) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x136),	/* type offset = 310 */
/* 836 (parameter bstrLic) */
        NdrFcShort(0x8b),	/* flags: must size, must free, in, by value */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x162),	/* type offset = 354 */
/* 842 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x08,	/* FC_LONG */
        0x0,
/* 848 (procedure IAxWinHostWindowLic::CreateControlLicEx) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xa),	/* method 10 */
        NdrFcShort(0x48),	/* stack size = 72 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x08,	/* 8 params */
        0x14,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x08),
        0x08,
        0x80,
        0x81,
        0x82,
        0x83,
        0x84,
        0x85,
        0x86,
        0x87,
        0x00,
/* 884 (parameter lpTricsData) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x16e),	/* type offset = 366 */
/* 890 (parameter hWnd) */
        NdrFcShort(0x8b),	/* flags: must size, must free, in, by value */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x170),	/* type offset = 368 */
/* 896 (parameter pStream) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x17a),	/* type offset = 378 */
/* 902 (parameter ppUnk) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x19e),	/* type offset = 414 */
/* 908 (parameter riidAdvise) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0xb6),	/* type offset = 182 */
/* 914 (parameter punkAdvise) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x1a6),	/* type offset = 422 */
/* 920 (parameter bstrLic) */
        NdrFcShort(0x8b),	/* flags: must size, must free, in, by value */
        NdrFcShort(0x38),	/* stack offset = 56 */
        NdrFcShort(0x1b8),	/* type offset = 440 */
/* 926 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x40),	/* stack offset = 64 */
        0x08,	/* FC_LONG */
        0x0,
/* 932 (procedure IAxWinAmbientDispatch::AllowWindowlessActivation) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x6),	/* client buffer = 6 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 962 (parameter bCanWindowlessActivate) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 968 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 974 (procedure IAxWinAmbientDispatch::AllowWindowlessActivation) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0xe),	/* server buffer = 14 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1004 (parameter pbCanWindowlessActivate) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1010 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1016 (procedure IAxWinAmbientDispatch::BackColor) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1046 (parameter clrBackground) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1052 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1058 (procedure IAxWinAmbientDispatch::BackColor) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xa),	/* method 10 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1088 (parameter pclrBackground) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1094 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1100 (procedure IAxWinAmbientDispatch::ForeColor) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xb),	/* method 11 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1130 (parameter clrForeground) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1136 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1142 (procedure IAxWinAmbientDispatch::ForeColor) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xc),	/* method 12 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1172 (parameter pclrForeground) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1178 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1184 (procedure IAxWinAmbientDispatch::LocaleID) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xd),	/* method 13 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1214 (parameter lcidLocaleID) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1220 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1226 (procedure IAxWinAmbientDispatch::LocaleID) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xe),	/* method 14 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1256 (parameter plcidLocaleID) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1262 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1268 (procedure IAxWinAmbientDispatch::UserMode) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xf),	/* method 15 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x6),	/* client buffer = 6 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1298 (parameter bUserMode) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1304 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1310 (procedure IAxWinAmbientDispatch::UserMode) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x10),	/* method 16 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0xe),	/* server buffer = 14 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1340 (parameter pbUserMode) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1346 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1352 (procedure IAxWinAmbientDispatch::DisplayAsDefault) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x11),	/* method 17 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x6),	/* client buffer = 6 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1382 (parameter bDisplayAsDefault) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1388 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1394 (procedure IAxWinAmbientDispatch::DisplayAsDefault) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x12),	/* method 18 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0xe),	/* server buffer = 14 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1424 (parameter pbDisplayAsDefault) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1430 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1436 (procedure IAxWinAmbientDispatch::Font) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x13),	/* method 19 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1466 (parameter pFont) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x1da),	/* type offset = 474 */
/* 1472 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1478 (procedure IAxWinAmbientDispatch::Font) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x14),	/* method 20 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1508 (parameter pFont) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x1fe),	/* type offset = 510 */
/* 1514 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1520 (procedure IAxWinAmbientDispatch::MessageReflect) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x15),	/* method 21 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x6),	/* client buffer = 6 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1550 (parameter bMsgReflect) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1556 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1562 (procedure IAxWinAmbientDispatch::MessageReflect) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x16),	/* method 22 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0xe),	/* server buffer = 14 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1592 (parameter pbMsgReflect) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1598 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1604 (procedure IAxWinAmbientDispatch::ShowGrabHandles) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x17),	/* method 23 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0xe),	/* server buffer = 14 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1634 (parameter pbShowGrabHandles) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1640 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1646 (procedure IAxWinAmbientDispatch::ShowHatching) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x18),	/* method 24 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0xe),	/* server buffer = 14 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1676 (parameter pbShowHatching) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1682 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1688 (procedure IAxWinAmbientDispatch::DocHostFlags) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x19),	/* method 25 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1718 (parameter dwDocHostFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1724 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1730 (procedure IAxWinAmbientDispatch::DocHostFlags) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x1a),	/* method 26 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1760 (parameter pdwDocHostFlags) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1766 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1772 (procedure IAxWinAmbientDispatch::DocHostDoubleClickFlags) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x1b),	/* method 27 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1802 (parameter dwDocHostDoubleClickFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1808 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1814 (procedure IAxWinAmbientDispatch::DocHostDoubleClickFlags) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x1c),	/* method 28 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1844 (parameter pdwDocHostDoubleClickFlags) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1850 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1856 (procedure IAxWinAmbientDispatch::AllowContextMenu) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x1d),	/* method 29 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x6),	/* client buffer = 6 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1886 (parameter bAllowContextMenu) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1892 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1898 (procedure IAxWinAmbientDispatch::AllowContextMenu) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x1e),	/* method 30 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0xe),	/* server buffer = 14 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1928 (parameter pbAllowContextMenu) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1934 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1940 (procedure IAxWinAmbientDispatch::AllowShowUI) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x1f),	/* method 31 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x6),	/* client buffer = 6 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 1970 (parameter bAllowShowUI) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1976 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1982 (procedure IAxWinAmbientDispatch::AllowShowUI) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x20),	/* method 32 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0xe),	/* server buffer = 14 */
        0x44,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 2012 (parameter pbAllowShowUI) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 2018 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 2024 (procedure IAxWinAmbientDispatch::OptionKeyPath) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x21),	/* method 33 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 2054 (parameter bstrOptionKeyPath) */
        NdrFcShort(0x8b),	/* flags: must size, must free, in, by value */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x21e),	/* type offset = 542 */
/* 2060 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 2066 (procedure IAxWinAmbientDispatch::OptionKeyPath) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x22),	/* method 34 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 2096 (parameter pbstrOptionKeyPath) */
        NdrFcShort(0x2113),	/* flags: must size, must free, out, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x228),	/* type offset = 552 */
/* 2102 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 2108 (procedure IAxWinAmbientDispatchEx::SetAmbientDispatch) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x23),	/* method 35 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 2138 (parameter pDispatch) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x236),	/* type offset = 566 */
/* 2144 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 2150 (procedure IInternalConnection::AddConnection) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x0c,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x01),
        0x01,
        0x80,
/* 2178 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 2184 (procedure IInternalConnection::ReleaseConnection) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x0c,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x01),
        0x01,
        0x80,
/* 2212 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 2218 (procedure IAccessibleProxy::SetServer) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x03),
        0x03,
        0x80,
        0x81,
        0x82,
/* 2248 (parameter pAccessible) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x248),	/* type offset = 584 */
/* 2254 (parameter pServer) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x25a),	/* type offset = 602 */
/* 2260 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 2266 (procedure IAccessibleServer::SetProxy) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 2296 (parameter pUnknown) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x26c),	/* type offset = 620 */
/* 2302 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 2308 (procedure IAccessibleServer::GetHWND) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 2338 (parameter phWnd) */
        NdrFcShort(0x2113),	/* flags: must size, must free, out, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x27e),	/* type offset = 638 */
/* 2344 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 2350 (procedure IAccessibleServer::GetEnumVariant) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0e,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x02),
        0x02,
        0x80,
        0x81,
        0x00,
/* 2380 (parameter ppEnumVariant) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x29e),	/* type offset = 670 */
/* 2386 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/*  4 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 6 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/*  8 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 10 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 12 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 14 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 16 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 18 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 20 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 22 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 24 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 26 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 28 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 30 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 32 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 34 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 36 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 38 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 40 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 42 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 44 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 46 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 48 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 50 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 52 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 54 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 56 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 58 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 60 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 62 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 64 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 66 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 68 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 70 (RemotableHandle) */
        0x2a,	/* FC_ENCAPSULATED_UNION */
        0x48,	/* Switch type= FC_LONG */
        NdrFcShort(0x4),	/* 4 */
        NdrFcShort(0x2),	/* 2 */
        NdrFcLong(0x48746457),	/* 1215587415 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x52746457),	/* 1383359575 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcShort(0xffff),
/* 90 (wireHWND) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffea),	/* Offset= -22 (70) */
/* 94 (HWND) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xfff4),	/* Offset= -12 (90) */
/* 104 (IStream *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0000000c),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 122 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 124 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 126 (HWND) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xffd4),	/* Offset= -44 (90) */
/* 136 (IStream *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0000000c),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 154 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 172 (IUnknown **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (154) */
/* 176 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 182 (IID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (176) */
        0x5b,	/* FC_END */
/* 194 (REFIID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (182) */
/* 198 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 216 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 234 (HWND) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xff68),	/* Offset= -152 (90) */
/* 244 (REFIID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffc0),	/* Offset= -64 (182) */
/* 248 (void *) */
        0x2f,  /* FC_IP */
        0x5c,  /* FC_PAD */
        0x2b,	/* Corr desc: parameter riid, FC_HYPER */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x5),
/* 256 (void **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xfff6),	/* Offset= -10 (248) */
/* 260 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 278 (IDocHostUIHandlerDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x425b5af0),
        NdrFcShort(0x65f1),
        NdrFcShort(0x11d1),
        0x96,
        0x11,
        0x00,
        0x00,
        0xf8,
        0x1e,
        0x0d,
        0x0d,

/* 296 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 298 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 300 (HWND) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xff26),	/* Offset= -218 (90) */
/* 310 (IStream *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0000000c),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 328 (unsigned short[]) */
        0x1b,	/* FC_CARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x2),	/* 2 */
        0x9,	/* Corr desc: field clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfffc),	/* offset = -4 */
        NdrFcShort(0x1),
        0x06,	/* FC_SHORT */
        0x5b,	/* FC_END */
/* 340 (FLAGGED_WORD_BLOB) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0xfff0),	/* Offset= -16 (328) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 350 (wireBSTR) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff4),	/* Offset= -12 (340) */
/* 354 (BSTR) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x1),	/* Function offset= 1 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xfff4),	/* Offset= -12 (350) */
/* 364 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 366 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 368 (HWND) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xfee2),	/* Offset= -286 (90) */
/* 378 (IStream *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0000000c),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 396 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 414 (IUnknown **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (396) */
/* 418 (REFIID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff12),	/* Offset= -238 (182) */
/* 422 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 440 (BSTR) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x1),	/* Function offset= 1 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xff9e),	/* Offset= -98 (350) */
/* 450 (VARIANT_BOOL *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 454 (OLE_COLOR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 458 (OLE_COLOR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 462 (LCID *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 466 (VARIANT_BOOL *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 470 (VARIANT_BOOL *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 474 (IFontDisp *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xbef6e003),
        NdrFcShort(0xa874),
        NdrFcShort(0x101a),
        0x8b,
        0xba,
        0x00,
        0xaa,
        0x00,
        0x30,
        0x0c,
        0xab,

/* 492 (IFontDisp *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xbef6e003),
        NdrFcShort(0xa874),
        NdrFcShort(0x101a),
        0x8b,
        0xba,
        0x00,
        0xaa,
        0x00,
        0x30,
        0x0c,
        0xab,

/* 510 (IFontDisp **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (492) */
/* 514 (VARIANT_BOOL *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 518 (VARIANT_BOOL *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 522 (VARIANT_BOOL *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 526 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 530 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 534 (VARIANT_BOOL *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 538 (VARIANT_BOOL *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 542 (BSTR) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x1),	/* Function offset= 1 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xff38),	/* Offset= -200 (350) */
/* 552 (BSTR) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x1),	/* Function offset= 1 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xff2e),	/* Offset= -210 (350) */
/* 562 (BSTR *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (552) */
/* 566 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 584 (IAccessible *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x618736e0),
        NdrFcShort(0x3c3d),
        NdrFcShort(0x11cf),
        0x81,
        0x0c,
        0x00,
        0xaa,
        0x00,
        0x38,
        0x9b,
        0x71,

/* 602 (IAccessibleServer *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x52c8fb5e),
        NdrFcShort(0xd779),
        NdrFcShort(0x4e77),
        0xae,
        0x9f,
        0xf6,
        0x11,
        0xfa,
        0x7e,
        0x9d,
        0x7a,

/* 620 (IAccessibleProxy *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x7a7d9dcf),
        NdrFcShort(0xb7a1),
        NdrFcShort(0x4019),
        0x90,
        0x31,
        0x25,
        0x82,
        0x68,
        0x84,
        0x69,
        0x80,

/* 638 (HWND) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xfdd4),	/* Offset= -556 (90) */
/* 648 (HWND *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (638) */
/* 652 (IEnumVARIANT *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020404),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 670 (IEnumVARIANT **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (652) */
        0x0
    }
};

static const CInterfaceProxyVtbl* const _atliface_ProxyVtblList[] =
{
    (const CInterfaceProxyVtbl*)&_IRegistrarProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IAxWinHostWindowProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IAxWinAmbientDispatchProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IAccessibleServerProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IInternalConnectionProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IRegistrarBaseProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IAxWinAmbientDispatchExProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IAxWinHostWindowLicProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IAccessibleProxyProxyVtbl,
    0
};

static const CInterfaceStubVtbl* const _atliface_StubVtblList[] =
{
    &_IRegistrarStubVtbl,
    &_IAxWinHostWindowStubVtbl,
    &_IAxWinAmbientDispatchStubVtbl,
    &_IAccessibleServerStubVtbl,
    &_IInternalConnectionStubVtbl,
    &_IRegistrarBaseStubVtbl,
    &_IAxWinAmbientDispatchExStubVtbl,
    &_IAxWinHostWindowLicStubVtbl,
    &_IAccessibleProxyStubVtbl,
    0
};

static PCInterfaceName const _atliface_InterfaceNamesList[] =
{
    "IRegistrar",
    "IAxWinHostWindow",
    "IAxWinAmbientDispatch",
    "IAccessibleServer",
    "IInternalConnection",
    "IRegistrarBase",
    "IAxWinAmbientDispatchEx",
    "IAxWinHostWindowLic",
    "IAccessibleProxy",
    0
};

static const IID * _atliface_BaseIIDList[] =
{
    0,
    0,
    &IID_IDispatch,  /* IAxWinAmbientDispatch */
    0,
    0,
    0,
    &IID_IDispatch,  /* IAxWinAmbientDispatchEx */
    0,
    0,
    0
};

static int __stdcall _atliface_IID_Lookup(const IID* pIID, int* pIndex)
{
    int low = 0, high = 8;

    while (low <= high)
    {
        int pos = (low + high) / 2;
        int res = IID_GENERIC_CHECK_IID(_atliface, pIID, pos);
        if (!res) { *pIndex = pos; return 1; }
        if (res > 0) low = pos + 1;
        else high = pos - 1;
    }
    return 0;
}

const ExtendedProxyFileInfo atliface_ProxyFileInfo =
{
    (const PCInterfaceProxyVtblList*)_atliface_ProxyVtblList,
    (const PCInterfaceStubVtblList*)_atliface_StubVtblList,
    _atliface_InterfaceNamesList,
    _atliface_BaseIIDList,
    _atliface_IID_Lookup,
    9,
    2,
    0,
    0,
    0,
    0
};
