/*** Autogenerated by WIDL 10.10 from ../../include/atliface.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __atliface_h__
#define __atliface_h__

/* Forward declarations */

#ifndef __IRegistrarBase_FWD_DEFINED__
#define __IRegistrarBase_FWD_DEFINED__
typedef interface IRegistrarBase IRegistrarBase;
#ifdef __cplusplus
interface IRegistrarBase;
#endif /* __cplusplus */
#endif

#ifndef __IRegistrar_FWD_DEFINED__
#define __IRegistrar_FWD_DEFINED__
typedef interface IRegistrar IRegistrar;
#ifdef __cplusplus
interface IRegistrar;
#endif /* __cplusplus */
#endif

#ifndef __IDocHostUIHandlerDispatch_FWD_DEFINED__
#define __IDocHostUIHandlerDispatch_FWD_DEFINED__
typedef interface IDocHostUIHandlerDispatch IDocHostUIHandlerDispatch;
#ifdef __cplusplus
interface IDocHostUIHandlerDispatch;
#endif /* __cplusplus */
#endif

#ifndef __IAxWinHostWindow_FWD_DEFINED__
#define __IAxWinHostWindow_FWD_DEFINED__
typedef interface IAxWinHostWindow IAxWinHostWindow;
#ifdef __cplusplus
interface IAxWinHostWindow;
#endif /* __cplusplus */
#endif

#ifndef __IAxWinHostWindowLic_FWD_DEFINED__
#define __IAxWinHostWindowLic_FWD_DEFINED__
typedef interface IAxWinHostWindowLic IAxWinHostWindowLic;
#ifdef __cplusplus
interface IAxWinHostWindowLic;
#endif /* __cplusplus */
#endif

#ifndef __IAxWinAmbientDispatch_FWD_DEFINED__
#define __IAxWinAmbientDispatch_FWD_DEFINED__
typedef interface IAxWinAmbientDispatch IAxWinAmbientDispatch;
#ifdef __cplusplus
interface IAxWinAmbientDispatch;
#endif /* __cplusplus */
#endif

#ifndef __IAxWinAmbientDispatchEx_FWD_DEFINED__
#define __IAxWinAmbientDispatchEx_FWD_DEFINED__
typedef interface IAxWinAmbientDispatchEx IAxWinAmbientDispatchEx;
#ifdef __cplusplus
interface IAxWinAmbientDispatchEx;
#endif /* __cplusplus */
#endif

#ifndef __IInternalConnection_FWD_DEFINED__
#define __IInternalConnection_FWD_DEFINED__
typedef interface IInternalConnection IInternalConnection;
#ifdef __cplusplus
interface IInternalConnection;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleProxy_FWD_DEFINED__
#define __IAccessibleProxy_FWD_DEFINED__
typedef interface IAccessibleProxy IAccessibleProxy;
#ifdef __cplusplus
interface IAccessibleProxy;
#endif /* __cplusplus */
#endif

#ifndef __IAccessibleServer_FWD_DEFINED__
#define __IAccessibleServer_FWD_DEFINED__
typedef interface IAccessibleServer IAccessibleServer;
#ifdef __cplusplus
interface IAccessibleServer;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <oaidl.h>
#include <ocidl.h>
#include <oleacc.h>

EXTERN_C const CLSID CLSID_Registrar;
/*****************************************************************************
 * IRegistrarBase interface
 */
#ifndef __IRegistrarBase_INTERFACE_DEFINED__
#define __IRegistrarBase_INTERFACE_DEFINED__

DEFINE_GUID(IID_IRegistrarBase, 0xe21f8a85, 0xb05d, 0x4243, 0x81,0x83, 0xc7,0xcb,0x40,0x55,0x88,0xf7);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("e21f8a85-b05d-4243-8183-c7cb405588f7")
IRegistrarBase : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE AddReplacement(
        LPCOLESTR key,
        LPCOLESTR item) = 0;

    virtual HRESULT STDMETHODCALLTYPE ClearReplacements(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IRegistrarBase, 0xe21f8a85, 0xb05d, 0x4243, 0x81,0x83, 0xc7,0xcb,0x40,0x55,0x88,0xf7)
#endif
#else
typedef struct IRegistrarBaseVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IRegistrarBase *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IRegistrarBase *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IRegistrarBase *This);

    /*** IRegistrarBase methods ***/
    HRESULT (STDMETHODCALLTYPE *AddReplacement)(
        IRegistrarBase *This,
        LPCOLESTR key,
        LPCOLESTR item);

    HRESULT (STDMETHODCALLTYPE *ClearReplacements)(
        IRegistrarBase *This);

    END_INTERFACE
} IRegistrarBaseVtbl;

interface IRegistrarBase {
    CONST_VTBL IRegistrarBaseVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IRegistrarBase_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IRegistrarBase_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IRegistrarBase_Release(This) (This)->lpVtbl->Release(This)
/*** IRegistrarBase methods ***/
#define IRegistrarBase_AddReplacement(This,key,item) (This)->lpVtbl->AddReplacement(This,key,item)
#define IRegistrarBase_ClearReplacements(This) (This)->lpVtbl->ClearReplacements(This)
#else
/*** IUnknown methods ***/
static inline HRESULT IRegistrarBase_QueryInterface(IRegistrarBase* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IRegistrarBase_AddRef(IRegistrarBase* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IRegistrarBase_Release(IRegistrarBase* This) {
    return This->lpVtbl->Release(This);
}
/*** IRegistrarBase methods ***/
static inline HRESULT IRegistrarBase_AddReplacement(IRegistrarBase* This,LPCOLESTR key,LPCOLESTR item) {
    return This->lpVtbl->AddReplacement(This,key,item);
}
static inline HRESULT IRegistrarBase_ClearReplacements(IRegistrarBase* This) {
    return This->lpVtbl->ClearReplacements(This);
}
#endif
#endif

#endif


#endif  /* __IRegistrarBase_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IRegistrar interface
 */
#ifndef __IRegistrar_INTERFACE_DEFINED__
#define __IRegistrar_INTERFACE_DEFINED__

DEFINE_GUID(IID_IRegistrar, 0x44ec053b, 0x400f, 0x11d0, 0x9d,0xcd, 0x00,0xa0,0xc9,0x03,0x91,0xd3);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("44ec053b-400f-11d0-9dcd-00a0c90391d3")
IRegistrar : public IRegistrarBase
{
    virtual HRESULT STDMETHODCALLTYPE ResourceRegisterSz(
        LPCOLESTR resFileName,
        LPCOLESTR szID,
        LPCOLESTR szType) = 0;

    virtual HRESULT STDMETHODCALLTYPE ResourceUnregisterSz(
        LPCOLESTR resFileName,
        LPCOLESTR szID,
        LPCOLESTR szType) = 0;

    virtual HRESULT STDMETHODCALLTYPE FileRegister(
        LPCOLESTR fileName) = 0;

    virtual HRESULT STDMETHODCALLTYPE FileUnregister(
        LPCOLESTR fileName) = 0;

    virtual HRESULT STDMETHODCALLTYPE StringRegister(
        LPCOLESTR data) = 0;

    virtual HRESULT STDMETHODCALLTYPE StringUnregister(
        LPCOLESTR data) = 0;

    virtual HRESULT STDMETHODCALLTYPE ResourceRegister(
        LPCOLESTR resFileName,
        UINT nID,
        LPCOLESTR szType) = 0;

    virtual HRESULT STDMETHODCALLTYPE ResourceUnregister(
        LPCOLESTR resFileName,
        UINT nID,
        LPCOLESTR szType) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IRegistrar, 0x44ec053b, 0x400f, 0x11d0, 0x9d,0xcd, 0x00,0xa0,0xc9,0x03,0x91,0xd3)
#endif
#else
typedef struct IRegistrarVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IRegistrar *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IRegistrar *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IRegistrar *This);

    /*** IRegistrarBase methods ***/
    HRESULT (STDMETHODCALLTYPE *AddReplacement)(
        IRegistrar *This,
        LPCOLESTR key,
        LPCOLESTR item);

    HRESULT (STDMETHODCALLTYPE *ClearReplacements)(
        IRegistrar *This);

    /*** IRegistrar methods ***/
    HRESULT (STDMETHODCALLTYPE *ResourceRegisterSz)(
        IRegistrar *This,
        LPCOLESTR resFileName,
        LPCOLESTR szID,
        LPCOLESTR szType);

    HRESULT (STDMETHODCALLTYPE *ResourceUnregisterSz)(
        IRegistrar *This,
        LPCOLESTR resFileName,
        LPCOLESTR szID,
        LPCOLESTR szType);

    HRESULT (STDMETHODCALLTYPE *FileRegister)(
        IRegistrar *This,
        LPCOLESTR fileName);

    HRESULT (STDMETHODCALLTYPE *FileUnregister)(
        IRegistrar *This,
        LPCOLESTR fileName);

    HRESULT (STDMETHODCALLTYPE *StringRegister)(
        IRegistrar *This,
        LPCOLESTR data);

    HRESULT (STDMETHODCALLTYPE *StringUnregister)(
        IRegistrar *This,
        LPCOLESTR data);

    HRESULT (STDMETHODCALLTYPE *ResourceRegister)(
        IRegistrar *This,
        LPCOLESTR resFileName,
        UINT nID,
        LPCOLESTR szType);

    HRESULT (STDMETHODCALLTYPE *ResourceUnregister)(
        IRegistrar *This,
        LPCOLESTR resFileName,
        UINT nID,
        LPCOLESTR szType);

    END_INTERFACE
} IRegistrarVtbl;

interface IRegistrar {
    CONST_VTBL IRegistrarVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IRegistrar_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IRegistrar_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IRegistrar_Release(This) (This)->lpVtbl->Release(This)
/*** IRegistrarBase methods ***/
#define IRegistrar_AddReplacement(This,key,item) (This)->lpVtbl->AddReplacement(This,key,item)
#define IRegistrar_ClearReplacements(This) (This)->lpVtbl->ClearReplacements(This)
/*** IRegistrar methods ***/
#define IRegistrar_ResourceRegisterSz(This,resFileName,szID,szType) (This)->lpVtbl->ResourceRegisterSz(This,resFileName,szID,szType)
#define IRegistrar_ResourceUnregisterSz(This,resFileName,szID,szType) (This)->lpVtbl->ResourceUnregisterSz(This,resFileName,szID,szType)
#define IRegistrar_FileRegister(This,fileName) (This)->lpVtbl->FileRegister(This,fileName)
#define IRegistrar_FileUnregister(This,fileName) (This)->lpVtbl->FileUnregister(This,fileName)
#define IRegistrar_StringRegister(This,data) (This)->lpVtbl->StringRegister(This,data)
#define IRegistrar_StringUnregister(This,data) (This)->lpVtbl->StringUnregister(This,data)
#define IRegistrar_ResourceRegister(This,resFileName,nID,szType) (This)->lpVtbl->ResourceRegister(This,resFileName,nID,szType)
#define IRegistrar_ResourceUnregister(This,resFileName,nID,szType) (This)->lpVtbl->ResourceUnregister(This,resFileName,nID,szType)
#else
/*** IUnknown methods ***/
static inline HRESULT IRegistrar_QueryInterface(IRegistrar* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IRegistrar_AddRef(IRegistrar* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IRegistrar_Release(IRegistrar* This) {
    return This->lpVtbl->Release(This);
}
/*** IRegistrarBase methods ***/
static inline HRESULT IRegistrar_AddReplacement(IRegistrar* This,LPCOLESTR key,LPCOLESTR item) {
    return This->lpVtbl->AddReplacement(This,key,item);
}
static inline HRESULT IRegistrar_ClearReplacements(IRegistrar* This) {
    return This->lpVtbl->ClearReplacements(This);
}
/*** IRegistrar methods ***/
static inline HRESULT IRegistrar_ResourceRegisterSz(IRegistrar* This,LPCOLESTR resFileName,LPCOLESTR szID,LPCOLESTR szType) {
    return This->lpVtbl->ResourceRegisterSz(This,resFileName,szID,szType);
}
static inline HRESULT IRegistrar_ResourceUnregisterSz(IRegistrar* This,LPCOLESTR resFileName,LPCOLESTR szID,LPCOLESTR szType) {
    return This->lpVtbl->ResourceUnregisterSz(This,resFileName,szID,szType);
}
static inline HRESULT IRegistrar_FileRegister(IRegistrar* This,LPCOLESTR fileName) {
    return This->lpVtbl->FileRegister(This,fileName);
}
static inline HRESULT IRegistrar_FileUnregister(IRegistrar* This,LPCOLESTR fileName) {
    return This->lpVtbl->FileUnregister(This,fileName);
}
static inline HRESULT IRegistrar_StringRegister(IRegistrar* This,LPCOLESTR data) {
    return This->lpVtbl->StringRegister(This,data);
}
static inline HRESULT IRegistrar_StringUnregister(IRegistrar* This,LPCOLESTR data) {
    return This->lpVtbl->StringUnregister(This,data);
}
static inline HRESULT IRegistrar_ResourceRegister(IRegistrar* This,LPCOLESTR resFileName,UINT nID,LPCOLESTR szType) {
    return This->lpVtbl->ResourceRegister(This,resFileName,nID,szType);
}
static inline HRESULT IRegistrar_ResourceUnregister(IRegistrar* This,LPCOLESTR resFileName,UINT nID,LPCOLESTR szType) {
    return This->lpVtbl->ResourceUnregister(This,resFileName,nID,szType);
}
#endif
#endif

#endif


#endif  /* __IRegistrar_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IDocHostUIHandlerDispatch interface
 */
#ifndef __IDocHostUIHandlerDispatch_INTERFACE_DEFINED__
#define __IDocHostUIHandlerDispatch_INTERFACE_DEFINED__

typedef enum tagDOCHOSTUIDBLCLKDispatch {
    docHostUIDblClkDEFAULT = 0,
    docHostUIDblClkSHOWPROPERTIES = 1,
    docHostUIDblClkSHOWCODE = 2
} DOCHOSTUIDBLCLKDispatch;
typedef enum tagDocHostUIFlagDispatch {
    docHostUIFlagDIALOG = 1,
    docHostUIFlagDISABLE_HELP_MENU = 2,
    docHostUIFlagNO3DBORDER = 4,
    docHostUIFlagSCROLL_NO = 8,
    docHostUIFlagDISABLE_SCRIPT_INACTIVE = 16,
    docHostUIFlagOPENNEWWIN = 32,
    docHostUIFlagDISABLE_OFFSCREEN = 64,
    docHostUIFlagFLAT_SCROLLBAR = 128,
    docHostUIFlagDIV_BLOCKDEFAULT = 256,
    docHostUIFlagACTIVATE_CLIENTHIT_ONLY = 512
} DocHostUIFlagDispatch;
DEFINE_GUID(IID_IDocHostUIHandlerDispatch, 0x425b5af0, 0x65f1, 0x11d1, 0x96,0x11, 0x00,0x00,0xf8,0x1e,0x0d,0x0d);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("425b5af0-65f1-11d1-9611-0000f81e0d0d")
IDocHostUIHandlerDispatch : public IDispatch
{
    virtual HRESULT STDMETHODCALLTYPE ShowContextMenu(
        DWORD dwID,
        DWORD x,
        DWORD y,
        IUnknown *pcmdtReserved,
        IDispatch *pdispReserved,
        HRESULT *dwRetVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetHostInfo(
        DWORD *pdwFlags,
        DWORD *pdwDoubleClick) = 0;

    virtual HRESULT STDMETHODCALLTYPE ShowUI(
        DWORD dwID,
        IUnknown *pActiveObject,
        IUnknown *pCommandTarget,
        IUnknown *pFrame,
        IUnknown *pDoc,
        HRESULT *dwRetVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE HideUI(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE UpdateUI(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE EnableModeless(
        VARIANT_BOOL fEnable) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnDocWindowActivate(
        VARIANT_BOOL fActivate) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnFrameWindowActivate(
        VARIANT_BOOL fActivate) = 0;

    virtual HRESULT STDMETHODCALLTYPE ResizeBorder(
        LONG left,
        LONG top,
        LONG right,
        LONG bottom,
        IUnknown *pUIWindow,
        VARIANT_BOOL fFrameWindow) = 0;

    virtual HRESULT STDMETHODCALLTYPE TranslateAccelerator(
        DWORD_PTR hWnd,
        DWORD nMessage,
        DWORD_PTR wParam,
        DWORD_PTR lParam,
        BSTR bstrGuidCmdGroup,
        DWORD nCmdID,
        HRESULT *dwRetVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetOptionKeyPath(
        BSTR *pbstrKey,
        DWORD dw) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetDropTarget(
        IUnknown *pDropTarget,
        IUnknown **ppDropTarget) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetExternal(
        IDispatch **ppDispatch) = 0;

    virtual HRESULT STDMETHODCALLTYPE TranslateUrl(
        DWORD dwTranslate,
        BSTR bstrURLIn,
        BSTR *pbstrURLOut) = 0;

    virtual HRESULT STDMETHODCALLTYPE FilterDataObject(
        IUnknown *pDO,
        IUnknown **ppDORet) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDocHostUIHandlerDispatch, 0x425b5af0, 0x65f1, 0x11d1, 0x96,0x11, 0x00,0x00,0xf8,0x1e,0x0d,0x0d)
#endif
#else
typedef struct IDocHostUIHandlerDispatchVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDocHostUIHandlerDispatch *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDocHostUIHandlerDispatch *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDocHostUIHandlerDispatch *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        IDocHostUIHandlerDispatch *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        IDocHostUIHandlerDispatch *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        IDocHostUIHandlerDispatch *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        IDocHostUIHandlerDispatch *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** IDocHostUIHandlerDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *ShowContextMenu)(
        IDocHostUIHandlerDispatch *This,
        DWORD dwID,
        DWORD x,
        DWORD y,
        IUnknown *pcmdtReserved,
        IDispatch *pdispReserved,
        HRESULT *dwRetVal);

    HRESULT (STDMETHODCALLTYPE *GetHostInfo)(
        IDocHostUIHandlerDispatch *This,
        DWORD *pdwFlags,
        DWORD *pdwDoubleClick);

    HRESULT (STDMETHODCALLTYPE *ShowUI)(
        IDocHostUIHandlerDispatch *This,
        DWORD dwID,
        IUnknown *pActiveObject,
        IUnknown *pCommandTarget,
        IUnknown *pFrame,
        IUnknown *pDoc,
        HRESULT *dwRetVal);

    HRESULT (STDMETHODCALLTYPE *HideUI)(
        IDocHostUIHandlerDispatch *This);

    HRESULT (STDMETHODCALLTYPE *UpdateUI)(
        IDocHostUIHandlerDispatch *This);

    HRESULT (STDMETHODCALLTYPE *EnableModeless)(
        IDocHostUIHandlerDispatch *This,
        VARIANT_BOOL fEnable);

    HRESULT (STDMETHODCALLTYPE *OnDocWindowActivate)(
        IDocHostUIHandlerDispatch *This,
        VARIANT_BOOL fActivate);

    HRESULT (STDMETHODCALLTYPE *OnFrameWindowActivate)(
        IDocHostUIHandlerDispatch *This,
        VARIANT_BOOL fActivate);

    HRESULT (STDMETHODCALLTYPE *ResizeBorder)(
        IDocHostUIHandlerDispatch *This,
        LONG left,
        LONG top,
        LONG right,
        LONG bottom,
        IUnknown *pUIWindow,
        VARIANT_BOOL fFrameWindow);

    HRESULT (STDMETHODCALLTYPE *TranslateAccelerator)(
        IDocHostUIHandlerDispatch *This,
        DWORD_PTR hWnd,
        DWORD nMessage,
        DWORD_PTR wParam,
        DWORD_PTR lParam,
        BSTR bstrGuidCmdGroup,
        DWORD nCmdID,
        HRESULT *dwRetVal);

    HRESULT (STDMETHODCALLTYPE *GetOptionKeyPath)(
        IDocHostUIHandlerDispatch *This,
        BSTR *pbstrKey,
        DWORD dw);

    HRESULT (STDMETHODCALLTYPE *GetDropTarget)(
        IDocHostUIHandlerDispatch *This,
        IUnknown *pDropTarget,
        IUnknown **ppDropTarget);

    HRESULT (STDMETHODCALLTYPE *GetExternal)(
        IDocHostUIHandlerDispatch *This,
        IDispatch **ppDispatch);

    HRESULT (STDMETHODCALLTYPE *TranslateUrl)(
        IDocHostUIHandlerDispatch *This,
        DWORD dwTranslate,
        BSTR bstrURLIn,
        BSTR *pbstrURLOut);

    HRESULT (STDMETHODCALLTYPE *FilterDataObject)(
        IDocHostUIHandlerDispatch *This,
        IUnknown *pDO,
        IUnknown **ppDORet);

    END_INTERFACE
} IDocHostUIHandlerDispatchVtbl;

interface IDocHostUIHandlerDispatch {
    CONST_VTBL IDocHostUIHandlerDispatchVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDocHostUIHandlerDispatch_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IDocHostUIHandlerDispatch_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDocHostUIHandlerDispatch_Release(This) (This)->lpVtbl->Release(This)
/*** IDispatch methods ***/
#define IDocHostUIHandlerDispatch_GetTypeInfoCount(This,pctinfo) (This)->lpVtbl->GetTypeInfoCount(This,pctinfo)
#define IDocHostUIHandlerDispatch_GetTypeInfo(This,iTInfo,lcid,ppTInfo) (This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo)
#define IDocHostUIHandlerDispatch_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) (This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId)
#define IDocHostUIHandlerDispatch_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) (This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr)
/*** IDocHostUIHandlerDispatch methods ***/
#define IDocHostUIHandlerDispatch_ShowContextMenu(This,dwID,x,y,pcmdtReserved,pdispReserved,dwRetVal) (This)->lpVtbl->ShowContextMenu(This,dwID,x,y,pcmdtReserved,pdispReserved,dwRetVal)
#define IDocHostUIHandlerDispatch_GetHostInfo(This,pdwFlags,pdwDoubleClick) (This)->lpVtbl->GetHostInfo(This,pdwFlags,pdwDoubleClick)
#define IDocHostUIHandlerDispatch_ShowUI(This,dwID,pActiveObject,pCommandTarget,pFrame,pDoc,dwRetVal) (This)->lpVtbl->ShowUI(This,dwID,pActiveObject,pCommandTarget,pFrame,pDoc,dwRetVal)
#define IDocHostUIHandlerDispatch_HideUI(This) (This)->lpVtbl->HideUI(This)
#define IDocHostUIHandlerDispatch_UpdateUI(This) (This)->lpVtbl->UpdateUI(This)
#define IDocHostUIHandlerDispatch_EnableModeless(This,fEnable) (This)->lpVtbl->EnableModeless(This,fEnable)
#define IDocHostUIHandlerDispatch_OnDocWindowActivate(This,fActivate) (This)->lpVtbl->OnDocWindowActivate(This,fActivate)
#define IDocHostUIHandlerDispatch_OnFrameWindowActivate(This,fActivate) (This)->lpVtbl->OnFrameWindowActivate(This,fActivate)
#define IDocHostUIHandlerDispatch_ResizeBorder(This,left,top,right,bottom,pUIWindow,fFrameWindow) (This)->lpVtbl->ResizeBorder(This,left,top,right,bottom,pUIWindow,fFrameWindow)
#define IDocHostUIHandlerDispatch_TranslateAccelerator(This,hWnd,nMessage,wParam,lParam,bstrGuidCmdGroup,nCmdID,dwRetVal) (This)->lpVtbl->TranslateAccelerator(This,hWnd,nMessage,wParam,lParam,bstrGuidCmdGroup,nCmdID,dwRetVal)
#define IDocHostUIHandlerDispatch_GetOptionKeyPath(This,pbstrKey,dw) (This)->lpVtbl->GetOptionKeyPath(This,pbstrKey,dw)
#define IDocHostUIHandlerDispatch_GetDropTarget(This,pDropTarget,ppDropTarget) (This)->lpVtbl->GetDropTarget(This,pDropTarget,ppDropTarget)
#define IDocHostUIHandlerDispatch_GetExternal(This,ppDispatch) (This)->lpVtbl->GetExternal(This,ppDispatch)
#define IDocHostUIHandlerDispatch_TranslateUrl(This,dwTranslate,bstrURLIn,pbstrURLOut) (This)->lpVtbl->TranslateUrl(This,dwTranslate,bstrURLIn,pbstrURLOut)
#define IDocHostUIHandlerDispatch_FilterDataObject(This,pDO,ppDORet) (This)->lpVtbl->FilterDataObject(This,pDO,ppDORet)
#else
/*** IUnknown methods ***/
static inline HRESULT IDocHostUIHandlerDispatch_QueryInterface(IDocHostUIHandlerDispatch* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IDocHostUIHandlerDispatch_AddRef(IDocHostUIHandlerDispatch* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IDocHostUIHandlerDispatch_Release(IDocHostUIHandlerDispatch* This) {
    return This->lpVtbl->Release(This);
}
/*** IDispatch methods ***/
static inline HRESULT IDocHostUIHandlerDispatch_GetTypeInfoCount(IDocHostUIHandlerDispatch* This,UINT *pctinfo) {
    return This->lpVtbl->GetTypeInfoCount(This,pctinfo);
}
static inline HRESULT IDocHostUIHandlerDispatch_GetTypeInfo(IDocHostUIHandlerDispatch* This,UINT iTInfo,LCID lcid,ITypeInfo **ppTInfo) {
    return This->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo);
}
static inline HRESULT IDocHostUIHandlerDispatch_GetIDsOfNames(IDocHostUIHandlerDispatch* This,REFIID riid,LPOLESTR *rgszNames,UINT cNames,LCID lcid,DISPID *rgDispId) {
    return This->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId);
}
static inline HRESULT IDocHostUIHandlerDispatch_Invoke(IDocHostUIHandlerDispatch* This,DISPID dispIdMember,REFIID riid,LCID lcid,WORD wFlags,DISPPARAMS *pDispParams,VARIANT *pVarResult,EXCEPINFO *pExcepInfo,UINT *puArgErr) {
    return This->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr);
}
/*** IDocHostUIHandlerDispatch methods ***/
static inline HRESULT IDocHostUIHandlerDispatch_ShowContextMenu(IDocHostUIHandlerDispatch* This,DWORD dwID,DWORD x,DWORD y,IUnknown *pcmdtReserved,IDispatch *pdispReserved,HRESULT *dwRetVal) {
    return This->lpVtbl->ShowContextMenu(This,dwID,x,y,pcmdtReserved,pdispReserved,dwRetVal);
}
static inline HRESULT IDocHostUIHandlerDispatch_GetHostInfo(IDocHostUIHandlerDispatch* This,DWORD *pdwFlags,DWORD *pdwDoubleClick) {
    return This->lpVtbl->GetHostInfo(This,pdwFlags,pdwDoubleClick);
}
static inline HRESULT IDocHostUIHandlerDispatch_ShowUI(IDocHostUIHandlerDispatch* This,DWORD dwID,IUnknown *pActiveObject,IUnknown *pCommandTarget,IUnknown *pFrame,IUnknown *pDoc,HRESULT *dwRetVal) {
    return This->lpVtbl->ShowUI(This,dwID,pActiveObject,pCommandTarget,pFrame,pDoc,dwRetVal);
}
static inline HRESULT IDocHostUIHandlerDispatch_HideUI(IDocHostUIHandlerDispatch* This) {
    return This->lpVtbl->HideUI(This);
}
static inline HRESULT IDocHostUIHandlerDispatch_UpdateUI(IDocHostUIHandlerDispatch* This) {
    return This->lpVtbl->UpdateUI(This);
}
static inline HRESULT IDocHostUIHandlerDispatch_EnableModeless(IDocHostUIHandlerDispatch* This,VARIANT_BOOL fEnable) {
    return This->lpVtbl->EnableModeless(This,fEnable);
}
static inline HRESULT IDocHostUIHandlerDispatch_OnDocWindowActivate(IDocHostUIHandlerDispatch* This,VARIANT_BOOL fActivate) {
    return This->lpVtbl->OnDocWindowActivate(This,fActivate);
}
static inline HRESULT IDocHostUIHandlerDispatch_OnFrameWindowActivate(IDocHostUIHandlerDispatch* This,VARIANT_BOOL fActivate) {
    return This->lpVtbl->OnFrameWindowActivate(This,fActivate);
}
static inline HRESULT IDocHostUIHandlerDispatch_ResizeBorder(IDocHostUIHandlerDispatch* This,LONG left,LONG top,LONG right,LONG bottom,IUnknown *pUIWindow,VARIANT_BOOL fFrameWindow) {
    return This->lpVtbl->ResizeBorder(This,left,top,right,bottom,pUIWindow,fFrameWindow);
}
static inline HRESULT IDocHostUIHandlerDispatch_TranslateAccelerator(IDocHostUIHandlerDispatch* This,DWORD_PTR hWnd,DWORD nMessage,DWORD_PTR wParam,DWORD_PTR lParam,BSTR bstrGuidCmdGroup,DWORD nCmdID,HRESULT *dwRetVal) {
    return This->lpVtbl->TranslateAccelerator(This,hWnd,nMessage,wParam,lParam,bstrGuidCmdGroup,nCmdID,dwRetVal);
}
static inline HRESULT IDocHostUIHandlerDispatch_GetOptionKeyPath(IDocHostUIHandlerDispatch* This,BSTR *pbstrKey,DWORD dw) {
    return This->lpVtbl->GetOptionKeyPath(This,pbstrKey,dw);
}
static inline HRESULT IDocHostUIHandlerDispatch_GetDropTarget(IDocHostUIHandlerDispatch* This,IUnknown *pDropTarget,IUnknown **ppDropTarget) {
    return This->lpVtbl->GetDropTarget(This,pDropTarget,ppDropTarget);
}
static inline HRESULT IDocHostUIHandlerDispatch_GetExternal(IDocHostUIHandlerDispatch* This,IDispatch **ppDispatch) {
    return This->lpVtbl->GetExternal(This,ppDispatch);
}
static inline HRESULT IDocHostUIHandlerDispatch_TranslateUrl(IDocHostUIHandlerDispatch* This,DWORD dwTranslate,BSTR bstrURLIn,BSTR *pbstrURLOut) {
    return This->lpVtbl->TranslateUrl(This,dwTranslate,bstrURLIn,pbstrURLOut);
}
static inline HRESULT IDocHostUIHandlerDispatch_FilterDataObject(IDocHostUIHandlerDispatch* This,IUnknown *pDO,IUnknown **ppDORet) {
    return This->lpVtbl->FilterDataObject(This,pDO,ppDORet);
}
#endif
#endif

#endif


#endif  /* __IDocHostUIHandlerDispatch_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAxWinHostWindow interface
 */
#ifndef __IAxWinHostWindow_INTERFACE_DEFINED__
#define __IAxWinHostWindow_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAxWinHostWindow, 0xb6ea2050, 0x048a, 0x11d1, 0x82,0xb9, 0x00,0xc0,0x4f,0xb9,0x94,0x2e);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("b6ea2050-048a-11d1-82b9-00c04fb9942e")
IAxWinHostWindow : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE CreateControl(
        LPCOLESTR lpTricsData,
        HWND hWnd,
        IStream *pStream) = 0;

    virtual HRESULT STDMETHODCALLTYPE CreateControlEx(
        LPCOLESTR lpTricsData,
        HWND hWnd,
        IStream *pStream,
        IUnknown **ppUnk,
        REFIID riidAdvise,
        IUnknown *punkAdvise) = 0;

    virtual HRESULT STDMETHODCALLTYPE AttachControl(
        IUnknown *pUnkControl,
        HWND hWnd) = 0;

    virtual HRESULT STDMETHODCALLTYPE QueryControl(
        REFIID riid,
        void **ppvObject) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetExternalDispatch(
        IDispatch *pDisp) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetExternalUIHandler(
        IDocHostUIHandlerDispatch *pDisp) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAxWinHostWindow, 0xb6ea2050, 0x048a, 0x11d1, 0x82,0xb9, 0x00,0xc0,0x4f,0xb9,0x94,0x2e)
#endif
#else
typedef struct IAxWinHostWindowVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAxWinHostWindow *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAxWinHostWindow *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAxWinHostWindow *This);

    /*** IAxWinHostWindow methods ***/
    HRESULT (STDMETHODCALLTYPE *CreateControl)(
        IAxWinHostWindow *This,
        LPCOLESTR lpTricsData,
        HWND hWnd,
        IStream *pStream);

    HRESULT (STDMETHODCALLTYPE *CreateControlEx)(
        IAxWinHostWindow *This,
        LPCOLESTR lpTricsData,
        HWND hWnd,
        IStream *pStream,
        IUnknown **ppUnk,
        REFIID riidAdvise,
        IUnknown *punkAdvise);

    HRESULT (STDMETHODCALLTYPE *AttachControl)(
        IAxWinHostWindow *This,
        IUnknown *pUnkControl,
        HWND hWnd);

    HRESULT (STDMETHODCALLTYPE *QueryControl)(
        IAxWinHostWindow *This,
        REFIID riid,
        void **ppvObject);

    HRESULT (STDMETHODCALLTYPE *SetExternalDispatch)(
        IAxWinHostWindow *This,
        IDispatch *pDisp);

    HRESULT (STDMETHODCALLTYPE *SetExternalUIHandler)(
        IAxWinHostWindow *This,
        IDocHostUIHandlerDispatch *pDisp);

    END_INTERFACE
} IAxWinHostWindowVtbl;

interface IAxWinHostWindow {
    CONST_VTBL IAxWinHostWindowVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAxWinHostWindow_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAxWinHostWindow_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAxWinHostWindow_Release(This) (This)->lpVtbl->Release(This)
/*** IAxWinHostWindow methods ***/
#define IAxWinHostWindow_CreateControl(This,lpTricsData,hWnd,pStream) (This)->lpVtbl->CreateControl(This,lpTricsData,hWnd,pStream)
#define IAxWinHostWindow_CreateControlEx(This,lpTricsData,hWnd,pStream,ppUnk,riidAdvise,punkAdvise) (This)->lpVtbl->CreateControlEx(This,lpTricsData,hWnd,pStream,ppUnk,riidAdvise,punkAdvise)
#define IAxWinHostWindow_AttachControl(This,pUnkControl,hWnd) (This)->lpVtbl->AttachControl(This,pUnkControl,hWnd)
#define IAxWinHostWindow_QueryControl(This,riid,ppvObject) (This)->lpVtbl->QueryControl(This,riid,ppvObject)
#define IAxWinHostWindow_SetExternalDispatch(This,pDisp) (This)->lpVtbl->SetExternalDispatch(This,pDisp)
#define IAxWinHostWindow_SetExternalUIHandler(This,pDisp) (This)->lpVtbl->SetExternalUIHandler(This,pDisp)
#else
/*** IUnknown methods ***/
static inline HRESULT IAxWinHostWindow_QueryInterface(IAxWinHostWindow* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IAxWinHostWindow_AddRef(IAxWinHostWindow* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IAxWinHostWindow_Release(IAxWinHostWindow* This) {
    return This->lpVtbl->Release(This);
}
/*** IAxWinHostWindow methods ***/
static inline HRESULT IAxWinHostWindow_CreateControl(IAxWinHostWindow* This,LPCOLESTR lpTricsData,HWND hWnd,IStream *pStream) {
    return This->lpVtbl->CreateControl(This,lpTricsData,hWnd,pStream);
}
static inline HRESULT IAxWinHostWindow_CreateControlEx(IAxWinHostWindow* This,LPCOLESTR lpTricsData,HWND hWnd,IStream *pStream,IUnknown **ppUnk,REFIID riidAdvise,IUnknown *punkAdvise) {
    return This->lpVtbl->CreateControlEx(This,lpTricsData,hWnd,pStream,ppUnk,riidAdvise,punkAdvise);
}
static inline HRESULT IAxWinHostWindow_AttachControl(IAxWinHostWindow* This,IUnknown *pUnkControl,HWND hWnd) {
    return This->lpVtbl->AttachControl(This,pUnkControl,hWnd);
}
static inline HRESULT IAxWinHostWindow_QueryControl(IAxWinHostWindow* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryControl(This,riid,ppvObject);
}
static inline HRESULT IAxWinHostWindow_SetExternalDispatch(IAxWinHostWindow* This,IDispatch *pDisp) {
    return This->lpVtbl->SetExternalDispatch(This,pDisp);
}
static inline HRESULT IAxWinHostWindow_SetExternalUIHandler(IAxWinHostWindow* This,IDocHostUIHandlerDispatch *pDisp) {
    return This->lpVtbl->SetExternalUIHandler(This,pDisp);
}
#endif
#endif

#endif


#endif  /* __IAxWinHostWindow_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAxWinHostWindowLic interface
 */
#ifndef __IAxWinHostWindowLic_INTERFACE_DEFINED__
#define __IAxWinHostWindowLic_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAxWinHostWindowLic, 0x3935bda8, 0x4ed9, 0x495c, 0x86,0x50, 0xe0,0x1f,0xc1,0xe3,0x8a,0x4b);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("3935bda8-4ed9-495c-8650-e01fc1e38a4b")
IAxWinHostWindowLic : public IAxWinHostWindow
{
    virtual HRESULT STDMETHODCALLTYPE CreateControlLic(
        LPCOLESTR lpTricsData,
        HWND hWnd,
        IStream *pStream,
        BSTR bstrLic) = 0;

    virtual HRESULT STDMETHODCALLTYPE CreateControlLicEx(
        LPCOLESTR lpTricsData,
        HWND hWnd,
        IStream *pStream,
        IUnknown **ppUnk,
        REFIID riidAdvise,
        IUnknown *punkAdvise,
        BSTR bstrLic) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAxWinHostWindowLic, 0x3935bda8, 0x4ed9, 0x495c, 0x86,0x50, 0xe0,0x1f,0xc1,0xe3,0x8a,0x4b)
#endif
#else
typedef struct IAxWinHostWindowLicVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAxWinHostWindowLic *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAxWinHostWindowLic *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAxWinHostWindowLic *This);

    /*** IAxWinHostWindow methods ***/
    HRESULT (STDMETHODCALLTYPE *CreateControl)(
        IAxWinHostWindowLic *This,
        LPCOLESTR lpTricsData,
        HWND hWnd,
        IStream *pStream);

    HRESULT (STDMETHODCALLTYPE *CreateControlEx)(
        IAxWinHostWindowLic *This,
        LPCOLESTR lpTricsData,
        HWND hWnd,
        IStream *pStream,
        IUnknown **ppUnk,
        REFIID riidAdvise,
        IUnknown *punkAdvise);

    HRESULT (STDMETHODCALLTYPE *AttachControl)(
        IAxWinHostWindowLic *This,
        IUnknown *pUnkControl,
        HWND hWnd);

    HRESULT (STDMETHODCALLTYPE *QueryControl)(
        IAxWinHostWindowLic *This,
        REFIID riid,
        void **ppvObject);

    HRESULT (STDMETHODCALLTYPE *SetExternalDispatch)(
        IAxWinHostWindowLic *This,
        IDispatch *pDisp);

    HRESULT (STDMETHODCALLTYPE *SetExternalUIHandler)(
        IAxWinHostWindowLic *This,
        IDocHostUIHandlerDispatch *pDisp);

    /*** IAxWinHostWindowLic methods ***/
    HRESULT (STDMETHODCALLTYPE *CreateControlLic)(
        IAxWinHostWindowLic *This,
        LPCOLESTR lpTricsData,
        HWND hWnd,
        IStream *pStream,
        BSTR bstrLic);

    HRESULT (STDMETHODCALLTYPE *CreateControlLicEx)(
        IAxWinHostWindowLic *This,
        LPCOLESTR lpTricsData,
        HWND hWnd,
        IStream *pStream,
        IUnknown **ppUnk,
        REFIID riidAdvise,
        IUnknown *punkAdvise,
        BSTR bstrLic);

    END_INTERFACE
} IAxWinHostWindowLicVtbl;

interface IAxWinHostWindowLic {
    CONST_VTBL IAxWinHostWindowLicVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAxWinHostWindowLic_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAxWinHostWindowLic_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAxWinHostWindowLic_Release(This) (This)->lpVtbl->Release(This)
/*** IAxWinHostWindow methods ***/
#define IAxWinHostWindowLic_CreateControl(This,lpTricsData,hWnd,pStream) (This)->lpVtbl->CreateControl(This,lpTricsData,hWnd,pStream)
#define IAxWinHostWindowLic_CreateControlEx(This,lpTricsData,hWnd,pStream,ppUnk,riidAdvise,punkAdvise) (This)->lpVtbl->CreateControlEx(This,lpTricsData,hWnd,pStream,ppUnk,riidAdvise,punkAdvise)
#define IAxWinHostWindowLic_AttachControl(This,pUnkControl,hWnd) (This)->lpVtbl->AttachControl(This,pUnkControl,hWnd)
#define IAxWinHostWindowLic_QueryControl(This,riid,ppvObject) (This)->lpVtbl->QueryControl(This,riid,ppvObject)
#define IAxWinHostWindowLic_SetExternalDispatch(This,pDisp) (This)->lpVtbl->SetExternalDispatch(This,pDisp)
#define IAxWinHostWindowLic_SetExternalUIHandler(This,pDisp) (This)->lpVtbl->SetExternalUIHandler(This,pDisp)
/*** IAxWinHostWindowLic methods ***/
#define IAxWinHostWindowLic_CreateControlLic(This,lpTricsData,hWnd,pStream,bstrLic) (This)->lpVtbl->CreateControlLic(This,lpTricsData,hWnd,pStream,bstrLic)
#define IAxWinHostWindowLic_CreateControlLicEx(This,lpTricsData,hWnd,pStream,ppUnk,riidAdvise,punkAdvise,bstrLic) (This)->lpVtbl->CreateControlLicEx(This,lpTricsData,hWnd,pStream,ppUnk,riidAdvise,punkAdvise,bstrLic)
#else
/*** IUnknown methods ***/
static inline HRESULT IAxWinHostWindowLic_QueryInterface(IAxWinHostWindowLic* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IAxWinHostWindowLic_AddRef(IAxWinHostWindowLic* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IAxWinHostWindowLic_Release(IAxWinHostWindowLic* This) {
    return This->lpVtbl->Release(This);
}
/*** IAxWinHostWindow methods ***/
static inline HRESULT IAxWinHostWindowLic_CreateControl(IAxWinHostWindowLic* This,LPCOLESTR lpTricsData,HWND hWnd,IStream *pStream) {
    return This->lpVtbl->CreateControl(This,lpTricsData,hWnd,pStream);
}
static inline HRESULT IAxWinHostWindowLic_CreateControlEx(IAxWinHostWindowLic* This,LPCOLESTR lpTricsData,HWND hWnd,IStream *pStream,IUnknown **ppUnk,REFIID riidAdvise,IUnknown *punkAdvise) {
    return This->lpVtbl->CreateControlEx(This,lpTricsData,hWnd,pStream,ppUnk,riidAdvise,punkAdvise);
}
static inline HRESULT IAxWinHostWindowLic_AttachControl(IAxWinHostWindowLic* This,IUnknown *pUnkControl,HWND hWnd) {
    return This->lpVtbl->AttachControl(This,pUnkControl,hWnd);
}
static inline HRESULT IAxWinHostWindowLic_QueryControl(IAxWinHostWindowLic* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryControl(This,riid,ppvObject);
}
static inline HRESULT IAxWinHostWindowLic_SetExternalDispatch(IAxWinHostWindowLic* This,IDispatch *pDisp) {
    return This->lpVtbl->SetExternalDispatch(This,pDisp);
}
static inline HRESULT IAxWinHostWindowLic_SetExternalUIHandler(IAxWinHostWindowLic* This,IDocHostUIHandlerDispatch *pDisp) {
    return This->lpVtbl->SetExternalUIHandler(This,pDisp);
}
/*** IAxWinHostWindowLic methods ***/
static inline HRESULT IAxWinHostWindowLic_CreateControlLic(IAxWinHostWindowLic* This,LPCOLESTR lpTricsData,HWND hWnd,IStream *pStream,BSTR bstrLic) {
    return This->lpVtbl->CreateControlLic(This,lpTricsData,hWnd,pStream,bstrLic);
}
static inline HRESULT IAxWinHostWindowLic_CreateControlLicEx(IAxWinHostWindowLic* This,LPCOLESTR lpTricsData,HWND hWnd,IStream *pStream,IUnknown **ppUnk,REFIID riidAdvise,IUnknown *punkAdvise,BSTR bstrLic) {
    return This->lpVtbl->CreateControlLicEx(This,lpTricsData,hWnd,pStream,ppUnk,riidAdvise,punkAdvise,bstrLic);
}
#endif
#endif

#endif


#endif  /* __IAxWinHostWindowLic_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAxWinAmbientDispatch interface
 */
#ifndef __IAxWinAmbientDispatch_INTERFACE_DEFINED__
#define __IAxWinAmbientDispatch_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAxWinAmbientDispatch, 0xb6ea2051, 0x048a, 0x11d1, 0x82,0xb9, 0x00,0xc0,0x4f,0xb9,0x94,0x2e);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("b6ea2051-048a-11d1-82b9-00c04fb9942e")
IAxWinAmbientDispatch : public IDispatch
{
    virtual HRESULT STDMETHODCALLTYPE put_AllowWindowlessActivation(
        VARIANT_BOOL bCanWindowlessActivate) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_AllowWindowlessActivation(
        VARIANT_BOOL *pbCanWindowlessActivate) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_BackColor(
        OLE_COLOR clrBackground) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_BackColor(
        OLE_COLOR *pclrBackground) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_ForeColor(
        OLE_COLOR clrForeground) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_ForeColor(
        OLE_COLOR *pclrForeground) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_LocaleID(
        LCID lcidLocaleID) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_LocaleID(
        LCID *plcidLocaleID) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_UserMode(
        VARIANT_BOOL bUserMode) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_UserMode(
        VARIANT_BOOL *pbUserMode) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_DisplayAsDefault(
        VARIANT_BOOL bDisplayAsDefault) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_DisplayAsDefault(
        VARIANT_BOOL *pbDisplayAsDefault) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_Font(
        IFontDisp *pFont) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_Font(
        IFontDisp **pFont) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_MessageReflect(
        VARIANT_BOOL bMsgReflect) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_MessageReflect(
        VARIANT_BOOL *pbMsgReflect) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_ShowGrabHandles(
        VARIANT_BOOL *pbShowGrabHandles) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_ShowHatching(
        VARIANT_BOOL *pbShowHatching) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_DocHostFlags(
        DWORD dwDocHostFlags) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_DocHostFlags(
        DWORD *pdwDocHostFlags) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_DocHostDoubleClickFlags(
        DWORD dwDocHostDoubleClickFlags) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_DocHostDoubleClickFlags(
        DWORD *pdwDocHostDoubleClickFlags) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_AllowContextMenu(
        VARIANT_BOOL bAllowContextMenu) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_AllowContextMenu(
        VARIANT_BOOL *pbAllowContextMenu) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_AllowShowUI(
        VARIANT_BOOL bAllowShowUI) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_AllowShowUI(
        VARIANT_BOOL *pbAllowShowUI) = 0;

    virtual HRESULT STDMETHODCALLTYPE put_OptionKeyPath(
        BSTR bstrOptionKeyPath) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_OptionKeyPath(
        BSTR *pbstrOptionKeyPath) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAxWinAmbientDispatch, 0xb6ea2051, 0x048a, 0x11d1, 0x82,0xb9, 0x00,0xc0,0x4f,0xb9,0x94,0x2e)
#endif
#else
typedef struct IAxWinAmbientDispatchVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAxWinAmbientDispatch *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAxWinAmbientDispatch *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAxWinAmbientDispatch *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        IAxWinAmbientDispatch *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        IAxWinAmbientDispatch *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        IAxWinAmbientDispatch *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        IAxWinAmbientDispatch *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** IAxWinAmbientDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *put_AllowWindowlessActivation)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL bCanWindowlessActivate);

    HRESULT (STDMETHODCALLTYPE *get_AllowWindowlessActivation)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL *pbCanWindowlessActivate);

    HRESULT (STDMETHODCALLTYPE *put_BackColor)(
        IAxWinAmbientDispatch *This,
        OLE_COLOR clrBackground);

    HRESULT (STDMETHODCALLTYPE *get_BackColor)(
        IAxWinAmbientDispatch *This,
        OLE_COLOR *pclrBackground);

    HRESULT (STDMETHODCALLTYPE *put_ForeColor)(
        IAxWinAmbientDispatch *This,
        OLE_COLOR clrForeground);

    HRESULT (STDMETHODCALLTYPE *get_ForeColor)(
        IAxWinAmbientDispatch *This,
        OLE_COLOR *pclrForeground);

    HRESULT (STDMETHODCALLTYPE *put_LocaleID)(
        IAxWinAmbientDispatch *This,
        LCID lcidLocaleID);

    HRESULT (STDMETHODCALLTYPE *get_LocaleID)(
        IAxWinAmbientDispatch *This,
        LCID *plcidLocaleID);

    HRESULT (STDMETHODCALLTYPE *put_UserMode)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL bUserMode);

    HRESULT (STDMETHODCALLTYPE *get_UserMode)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL *pbUserMode);

    HRESULT (STDMETHODCALLTYPE *put_DisplayAsDefault)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL bDisplayAsDefault);

    HRESULT (STDMETHODCALLTYPE *get_DisplayAsDefault)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL *pbDisplayAsDefault);

    HRESULT (STDMETHODCALLTYPE *put_Font)(
        IAxWinAmbientDispatch *This,
        IFontDisp *pFont);

    HRESULT (STDMETHODCALLTYPE *get_Font)(
        IAxWinAmbientDispatch *This,
        IFontDisp **pFont);

    HRESULT (STDMETHODCALLTYPE *put_MessageReflect)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL bMsgReflect);

    HRESULT (STDMETHODCALLTYPE *get_MessageReflect)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL *pbMsgReflect);

    HRESULT (STDMETHODCALLTYPE *get_ShowGrabHandles)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL *pbShowGrabHandles);

    HRESULT (STDMETHODCALLTYPE *get_ShowHatching)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL *pbShowHatching);

    HRESULT (STDMETHODCALLTYPE *put_DocHostFlags)(
        IAxWinAmbientDispatch *This,
        DWORD dwDocHostFlags);

    HRESULT (STDMETHODCALLTYPE *get_DocHostFlags)(
        IAxWinAmbientDispatch *This,
        DWORD *pdwDocHostFlags);

    HRESULT (STDMETHODCALLTYPE *put_DocHostDoubleClickFlags)(
        IAxWinAmbientDispatch *This,
        DWORD dwDocHostDoubleClickFlags);

    HRESULT (STDMETHODCALLTYPE *get_DocHostDoubleClickFlags)(
        IAxWinAmbientDispatch *This,
        DWORD *pdwDocHostDoubleClickFlags);

    HRESULT (STDMETHODCALLTYPE *put_AllowContextMenu)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL bAllowContextMenu);

    HRESULT (STDMETHODCALLTYPE *get_AllowContextMenu)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL *pbAllowContextMenu);

    HRESULT (STDMETHODCALLTYPE *put_AllowShowUI)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL bAllowShowUI);

    HRESULT (STDMETHODCALLTYPE *get_AllowShowUI)(
        IAxWinAmbientDispatch *This,
        VARIANT_BOOL *pbAllowShowUI);

    HRESULT (STDMETHODCALLTYPE *put_OptionKeyPath)(
        IAxWinAmbientDispatch *This,
        BSTR bstrOptionKeyPath);

    HRESULT (STDMETHODCALLTYPE *get_OptionKeyPath)(
        IAxWinAmbientDispatch *This,
        BSTR *pbstrOptionKeyPath);

    END_INTERFACE
} IAxWinAmbientDispatchVtbl;

interface IAxWinAmbientDispatch {
    CONST_VTBL IAxWinAmbientDispatchVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAxWinAmbientDispatch_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAxWinAmbientDispatch_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAxWinAmbientDispatch_Release(This) (This)->lpVtbl->Release(This)
/*** IDispatch methods ***/
#define IAxWinAmbientDispatch_GetTypeInfoCount(This,pctinfo) (This)->lpVtbl->GetTypeInfoCount(This,pctinfo)
#define IAxWinAmbientDispatch_GetTypeInfo(This,iTInfo,lcid,ppTInfo) (This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo)
#define IAxWinAmbientDispatch_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) (This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId)
#define IAxWinAmbientDispatch_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) (This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr)
/*** IAxWinAmbientDispatch methods ***/
#define IAxWinAmbientDispatch_put_AllowWindowlessActivation(This,bCanWindowlessActivate) (This)->lpVtbl->put_AllowWindowlessActivation(This,bCanWindowlessActivate)
#define IAxWinAmbientDispatch_get_AllowWindowlessActivation(This,pbCanWindowlessActivate) (This)->lpVtbl->get_AllowWindowlessActivation(This,pbCanWindowlessActivate)
#define IAxWinAmbientDispatch_put_BackColor(This,clrBackground) (This)->lpVtbl->put_BackColor(This,clrBackground)
#define IAxWinAmbientDispatch_get_BackColor(This,pclrBackground) (This)->lpVtbl->get_BackColor(This,pclrBackground)
#define IAxWinAmbientDispatch_put_ForeColor(This,clrForeground) (This)->lpVtbl->put_ForeColor(This,clrForeground)
#define IAxWinAmbientDispatch_get_ForeColor(This,pclrForeground) (This)->lpVtbl->get_ForeColor(This,pclrForeground)
#define IAxWinAmbientDispatch_put_LocaleID(This,lcidLocaleID) (This)->lpVtbl->put_LocaleID(This,lcidLocaleID)
#define IAxWinAmbientDispatch_get_LocaleID(This,plcidLocaleID) (This)->lpVtbl->get_LocaleID(This,plcidLocaleID)
#define IAxWinAmbientDispatch_put_UserMode(This,bUserMode) (This)->lpVtbl->put_UserMode(This,bUserMode)
#define IAxWinAmbientDispatch_get_UserMode(This,pbUserMode) (This)->lpVtbl->get_UserMode(This,pbUserMode)
#define IAxWinAmbientDispatch_put_DisplayAsDefault(This,bDisplayAsDefault) (This)->lpVtbl->put_DisplayAsDefault(This,bDisplayAsDefault)
#define IAxWinAmbientDispatch_get_DisplayAsDefault(This,pbDisplayAsDefault) (This)->lpVtbl->get_DisplayAsDefault(This,pbDisplayAsDefault)
#define IAxWinAmbientDispatch_put_Font(This,pFont) (This)->lpVtbl->put_Font(This,pFont)
#define IAxWinAmbientDispatch_get_Font(This,pFont) (This)->lpVtbl->get_Font(This,pFont)
#define IAxWinAmbientDispatch_put_MessageReflect(This,bMsgReflect) (This)->lpVtbl->put_MessageReflect(This,bMsgReflect)
#define IAxWinAmbientDispatch_get_MessageReflect(This,pbMsgReflect) (This)->lpVtbl->get_MessageReflect(This,pbMsgReflect)
#define IAxWinAmbientDispatch_get_ShowGrabHandles(This,pbShowGrabHandles) (This)->lpVtbl->get_ShowGrabHandles(This,pbShowGrabHandles)
#define IAxWinAmbientDispatch_get_ShowHatching(This,pbShowHatching) (This)->lpVtbl->get_ShowHatching(This,pbShowHatching)
#define IAxWinAmbientDispatch_put_DocHostFlags(This,dwDocHostFlags) (This)->lpVtbl->put_DocHostFlags(This,dwDocHostFlags)
#define IAxWinAmbientDispatch_get_DocHostFlags(This,pdwDocHostFlags) (This)->lpVtbl->get_DocHostFlags(This,pdwDocHostFlags)
#define IAxWinAmbientDispatch_put_DocHostDoubleClickFlags(This,dwDocHostDoubleClickFlags) (This)->lpVtbl->put_DocHostDoubleClickFlags(This,dwDocHostDoubleClickFlags)
#define IAxWinAmbientDispatch_get_DocHostDoubleClickFlags(This,pdwDocHostDoubleClickFlags) (This)->lpVtbl->get_DocHostDoubleClickFlags(This,pdwDocHostDoubleClickFlags)
#define IAxWinAmbientDispatch_put_AllowContextMenu(This,bAllowContextMenu) (This)->lpVtbl->put_AllowContextMenu(This,bAllowContextMenu)
#define IAxWinAmbientDispatch_get_AllowContextMenu(This,pbAllowContextMenu) (This)->lpVtbl->get_AllowContextMenu(This,pbAllowContextMenu)
#define IAxWinAmbientDispatch_put_AllowShowUI(This,bAllowShowUI) (This)->lpVtbl->put_AllowShowUI(This,bAllowShowUI)
#define IAxWinAmbientDispatch_get_AllowShowUI(This,pbAllowShowUI) (This)->lpVtbl->get_AllowShowUI(This,pbAllowShowUI)
#define IAxWinAmbientDispatch_put_OptionKeyPath(This,bstrOptionKeyPath) (This)->lpVtbl->put_OptionKeyPath(This,bstrOptionKeyPath)
#define IAxWinAmbientDispatch_get_OptionKeyPath(This,pbstrOptionKeyPath) (This)->lpVtbl->get_OptionKeyPath(This,pbstrOptionKeyPath)
#else
/*** IUnknown methods ***/
static inline HRESULT IAxWinAmbientDispatch_QueryInterface(IAxWinAmbientDispatch* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IAxWinAmbientDispatch_AddRef(IAxWinAmbientDispatch* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IAxWinAmbientDispatch_Release(IAxWinAmbientDispatch* This) {
    return This->lpVtbl->Release(This);
}
/*** IDispatch methods ***/
static inline HRESULT IAxWinAmbientDispatch_GetTypeInfoCount(IAxWinAmbientDispatch* This,UINT *pctinfo) {
    return This->lpVtbl->GetTypeInfoCount(This,pctinfo);
}
static inline HRESULT IAxWinAmbientDispatch_GetTypeInfo(IAxWinAmbientDispatch* This,UINT iTInfo,LCID lcid,ITypeInfo **ppTInfo) {
    return This->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo);
}
static inline HRESULT IAxWinAmbientDispatch_GetIDsOfNames(IAxWinAmbientDispatch* This,REFIID riid,LPOLESTR *rgszNames,UINT cNames,LCID lcid,DISPID *rgDispId) {
    return This->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId);
}
static inline HRESULT IAxWinAmbientDispatch_Invoke(IAxWinAmbientDispatch* This,DISPID dispIdMember,REFIID riid,LCID lcid,WORD wFlags,DISPPARAMS *pDispParams,VARIANT *pVarResult,EXCEPINFO *pExcepInfo,UINT *puArgErr) {
    return This->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr);
}
/*** IAxWinAmbientDispatch methods ***/
static inline HRESULT IAxWinAmbientDispatch_put_AllowWindowlessActivation(IAxWinAmbientDispatch* This,VARIANT_BOOL bCanWindowlessActivate) {
    return This->lpVtbl->put_AllowWindowlessActivation(This,bCanWindowlessActivate);
}
static inline HRESULT IAxWinAmbientDispatch_get_AllowWindowlessActivation(IAxWinAmbientDispatch* This,VARIANT_BOOL *pbCanWindowlessActivate) {
    return This->lpVtbl->get_AllowWindowlessActivation(This,pbCanWindowlessActivate);
}
static inline HRESULT IAxWinAmbientDispatch_put_BackColor(IAxWinAmbientDispatch* This,OLE_COLOR clrBackground) {
    return This->lpVtbl->put_BackColor(This,clrBackground);
}
static inline HRESULT IAxWinAmbientDispatch_get_BackColor(IAxWinAmbientDispatch* This,OLE_COLOR *pclrBackground) {
    return This->lpVtbl->get_BackColor(This,pclrBackground);
}
static inline HRESULT IAxWinAmbientDispatch_put_ForeColor(IAxWinAmbientDispatch* This,OLE_COLOR clrForeground) {
    return This->lpVtbl->put_ForeColor(This,clrForeground);
}
static inline HRESULT IAxWinAmbientDispatch_get_ForeColor(IAxWinAmbientDispatch* This,OLE_COLOR *pclrForeground) {
    return This->lpVtbl->get_ForeColor(This,pclrForeground);
}
static inline HRESULT IAxWinAmbientDispatch_put_LocaleID(IAxWinAmbientDispatch* This,LCID lcidLocaleID) {
    return This->lpVtbl->put_LocaleID(This,lcidLocaleID);
}
static inline HRESULT IAxWinAmbientDispatch_get_LocaleID(IAxWinAmbientDispatch* This,LCID *plcidLocaleID) {
    return This->lpVtbl->get_LocaleID(This,plcidLocaleID);
}
static inline HRESULT IAxWinAmbientDispatch_put_UserMode(IAxWinAmbientDispatch* This,VARIANT_BOOL bUserMode) {
    return This->lpVtbl->put_UserMode(This,bUserMode);
}
static inline HRESULT IAxWinAmbientDispatch_get_UserMode(IAxWinAmbientDispatch* This,VARIANT_BOOL *pbUserMode) {
    return This->lpVtbl->get_UserMode(This,pbUserMode);
}
static inline HRESULT IAxWinAmbientDispatch_put_DisplayAsDefault(IAxWinAmbientDispatch* This,VARIANT_BOOL bDisplayAsDefault) {
    return This->lpVtbl->put_DisplayAsDefault(This,bDisplayAsDefault);
}
static inline HRESULT IAxWinAmbientDispatch_get_DisplayAsDefault(IAxWinAmbientDispatch* This,VARIANT_BOOL *pbDisplayAsDefault) {
    return This->lpVtbl->get_DisplayAsDefault(This,pbDisplayAsDefault);
}
static inline HRESULT IAxWinAmbientDispatch_put_Font(IAxWinAmbientDispatch* This,IFontDisp *pFont) {
    return This->lpVtbl->put_Font(This,pFont);
}
static inline HRESULT IAxWinAmbientDispatch_get_Font(IAxWinAmbientDispatch* This,IFontDisp **pFont) {
    return This->lpVtbl->get_Font(This,pFont);
}
static inline HRESULT IAxWinAmbientDispatch_put_MessageReflect(IAxWinAmbientDispatch* This,VARIANT_BOOL bMsgReflect) {
    return This->lpVtbl->put_MessageReflect(This,bMsgReflect);
}
static inline HRESULT IAxWinAmbientDispatch_get_MessageReflect(IAxWinAmbientDispatch* This,VARIANT_BOOL *pbMsgReflect) {
    return This->lpVtbl->get_MessageReflect(This,pbMsgReflect);
}
static inline HRESULT IAxWinAmbientDispatch_get_ShowGrabHandles(IAxWinAmbientDispatch* This,VARIANT_BOOL *pbShowGrabHandles) {
    return This->lpVtbl->get_ShowGrabHandles(This,pbShowGrabHandles);
}
static inline HRESULT IAxWinAmbientDispatch_get_ShowHatching(IAxWinAmbientDispatch* This,VARIANT_BOOL *pbShowHatching) {
    return This->lpVtbl->get_ShowHatching(This,pbShowHatching);
}
static inline HRESULT IAxWinAmbientDispatch_put_DocHostFlags(IAxWinAmbientDispatch* This,DWORD dwDocHostFlags) {
    return This->lpVtbl->put_DocHostFlags(This,dwDocHostFlags);
}
static inline HRESULT IAxWinAmbientDispatch_get_DocHostFlags(IAxWinAmbientDispatch* This,DWORD *pdwDocHostFlags) {
    return This->lpVtbl->get_DocHostFlags(This,pdwDocHostFlags);
}
static inline HRESULT IAxWinAmbientDispatch_put_DocHostDoubleClickFlags(IAxWinAmbientDispatch* This,DWORD dwDocHostDoubleClickFlags) {
    return This->lpVtbl->put_DocHostDoubleClickFlags(This,dwDocHostDoubleClickFlags);
}
static inline HRESULT IAxWinAmbientDispatch_get_DocHostDoubleClickFlags(IAxWinAmbientDispatch* This,DWORD *pdwDocHostDoubleClickFlags) {
    return This->lpVtbl->get_DocHostDoubleClickFlags(This,pdwDocHostDoubleClickFlags);
}
static inline HRESULT IAxWinAmbientDispatch_put_AllowContextMenu(IAxWinAmbientDispatch* This,VARIANT_BOOL bAllowContextMenu) {
    return This->lpVtbl->put_AllowContextMenu(This,bAllowContextMenu);
}
static inline HRESULT IAxWinAmbientDispatch_get_AllowContextMenu(IAxWinAmbientDispatch* This,VARIANT_BOOL *pbAllowContextMenu) {
    return This->lpVtbl->get_AllowContextMenu(This,pbAllowContextMenu);
}
static inline HRESULT IAxWinAmbientDispatch_put_AllowShowUI(IAxWinAmbientDispatch* This,VARIANT_BOOL bAllowShowUI) {
    return This->lpVtbl->put_AllowShowUI(This,bAllowShowUI);
}
static inline HRESULT IAxWinAmbientDispatch_get_AllowShowUI(IAxWinAmbientDispatch* This,VARIANT_BOOL *pbAllowShowUI) {
    return This->lpVtbl->get_AllowShowUI(This,pbAllowShowUI);
}
static inline HRESULT IAxWinAmbientDispatch_put_OptionKeyPath(IAxWinAmbientDispatch* This,BSTR bstrOptionKeyPath) {
    return This->lpVtbl->put_OptionKeyPath(This,bstrOptionKeyPath);
}
static inline HRESULT IAxWinAmbientDispatch_get_OptionKeyPath(IAxWinAmbientDispatch* This,BSTR *pbstrOptionKeyPath) {
    return This->lpVtbl->get_OptionKeyPath(This,pbstrOptionKeyPath);
}
#endif
#endif

#endif


#endif  /* __IAxWinAmbientDispatch_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAxWinAmbientDispatchEx interface
 */
#ifndef __IAxWinAmbientDispatchEx_INTERFACE_DEFINED__
#define __IAxWinAmbientDispatchEx_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAxWinAmbientDispatchEx, 0xb2d0778b, 0xac99, 0x4c58, 0xa5,0xc8, 0xe7,0x72,0x4e,0x53,0x16,0xb5);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("b2d0778b-ac99-4c58-a5c8-e7724e5316b5")
IAxWinAmbientDispatchEx : public IAxWinAmbientDispatch
{
    virtual HRESULT STDMETHODCALLTYPE SetAmbientDispatch(
        IDispatch *pDispatch) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAxWinAmbientDispatchEx, 0xb2d0778b, 0xac99, 0x4c58, 0xa5,0xc8, 0xe7,0x72,0x4e,0x53,0x16,0xb5)
#endif
#else
typedef struct IAxWinAmbientDispatchExVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAxWinAmbientDispatchEx *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAxWinAmbientDispatchEx *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAxWinAmbientDispatchEx *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        IAxWinAmbientDispatchEx *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        IAxWinAmbientDispatchEx *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        IAxWinAmbientDispatchEx *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        IAxWinAmbientDispatchEx *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** IAxWinAmbientDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *put_AllowWindowlessActivation)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL bCanWindowlessActivate);

    HRESULT (STDMETHODCALLTYPE *get_AllowWindowlessActivation)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL *pbCanWindowlessActivate);

    HRESULT (STDMETHODCALLTYPE *put_BackColor)(
        IAxWinAmbientDispatchEx *This,
        OLE_COLOR clrBackground);

    HRESULT (STDMETHODCALLTYPE *get_BackColor)(
        IAxWinAmbientDispatchEx *This,
        OLE_COLOR *pclrBackground);

    HRESULT (STDMETHODCALLTYPE *put_ForeColor)(
        IAxWinAmbientDispatchEx *This,
        OLE_COLOR clrForeground);

    HRESULT (STDMETHODCALLTYPE *get_ForeColor)(
        IAxWinAmbientDispatchEx *This,
        OLE_COLOR *pclrForeground);

    HRESULT (STDMETHODCALLTYPE *put_LocaleID)(
        IAxWinAmbientDispatchEx *This,
        LCID lcidLocaleID);

    HRESULT (STDMETHODCALLTYPE *get_LocaleID)(
        IAxWinAmbientDispatchEx *This,
        LCID *plcidLocaleID);

    HRESULT (STDMETHODCALLTYPE *put_UserMode)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL bUserMode);

    HRESULT (STDMETHODCALLTYPE *get_UserMode)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL *pbUserMode);

    HRESULT (STDMETHODCALLTYPE *put_DisplayAsDefault)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL bDisplayAsDefault);

    HRESULT (STDMETHODCALLTYPE *get_DisplayAsDefault)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL *pbDisplayAsDefault);

    HRESULT (STDMETHODCALLTYPE *put_Font)(
        IAxWinAmbientDispatchEx *This,
        IFontDisp *pFont);

    HRESULT (STDMETHODCALLTYPE *get_Font)(
        IAxWinAmbientDispatchEx *This,
        IFontDisp **pFont);

    HRESULT (STDMETHODCALLTYPE *put_MessageReflect)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL bMsgReflect);

    HRESULT (STDMETHODCALLTYPE *get_MessageReflect)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL *pbMsgReflect);

    HRESULT (STDMETHODCALLTYPE *get_ShowGrabHandles)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL *pbShowGrabHandles);

    HRESULT (STDMETHODCALLTYPE *get_ShowHatching)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL *pbShowHatching);

    HRESULT (STDMETHODCALLTYPE *put_DocHostFlags)(
        IAxWinAmbientDispatchEx *This,
        DWORD dwDocHostFlags);

    HRESULT (STDMETHODCALLTYPE *get_DocHostFlags)(
        IAxWinAmbientDispatchEx *This,
        DWORD *pdwDocHostFlags);

    HRESULT (STDMETHODCALLTYPE *put_DocHostDoubleClickFlags)(
        IAxWinAmbientDispatchEx *This,
        DWORD dwDocHostDoubleClickFlags);

    HRESULT (STDMETHODCALLTYPE *get_DocHostDoubleClickFlags)(
        IAxWinAmbientDispatchEx *This,
        DWORD *pdwDocHostDoubleClickFlags);

    HRESULT (STDMETHODCALLTYPE *put_AllowContextMenu)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL bAllowContextMenu);

    HRESULT (STDMETHODCALLTYPE *get_AllowContextMenu)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL *pbAllowContextMenu);

    HRESULT (STDMETHODCALLTYPE *put_AllowShowUI)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL bAllowShowUI);

    HRESULT (STDMETHODCALLTYPE *get_AllowShowUI)(
        IAxWinAmbientDispatchEx *This,
        VARIANT_BOOL *pbAllowShowUI);

    HRESULT (STDMETHODCALLTYPE *put_OptionKeyPath)(
        IAxWinAmbientDispatchEx *This,
        BSTR bstrOptionKeyPath);

    HRESULT (STDMETHODCALLTYPE *get_OptionKeyPath)(
        IAxWinAmbientDispatchEx *This,
        BSTR *pbstrOptionKeyPath);

    /*** IAxWinAmbientDispatchEx methods ***/
    HRESULT (STDMETHODCALLTYPE *SetAmbientDispatch)(
        IAxWinAmbientDispatchEx *This,
        IDispatch *pDispatch);

    END_INTERFACE
} IAxWinAmbientDispatchExVtbl;

interface IAxWinAmbientDispatchEx {
    CONST_VTBL IAxWinAmbientDispatchExVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAxWinAmbientDispatchEx_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAxWinAmbientDispatchEx_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAxWinAmbientDispatchEx_Release(This) (This)->lpVtbl->Release(This)
/*** IDispatch methods ***/
#define IAxWinAmbientDispatchEx_GetTypeInfoCount(This,pctinfo) (This)->lpVtbl->GetTypeInfoCount(This,pctinfo)
#define IAxWinAmbientDispatchEx_GetTypeInfo(This,iTInfo,lcid,ppTInfo) (This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo)
#define IAxWinAmbientDispatchEx_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) (This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId)
#define IAxWinAmbientDispatchEx_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) (This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr)
/*** IAxWinAmbientDispatch methods ***/
#define IAxWinAmbientDispatchEx_put_AllowWindowlessActivation(This,bCanWindowlessActivate) (This)->lpVtbl->put_AllowWindowlessActivation(This,bCanWindowlessActivate)
#define IAxWinAmbientDispatchEx_get_AllowWindowlessActivation(This,pbCanWindowlessActivate) (This)->lpVtbl->get_AllowWindowlessActivation(This,pbCanWindowlessActivate)
#define IAxWinAmbientDispatchEx_put_BackColor(This,clrBackground) (This)->lpVtbl->put_BackColor(This,clrBackground)
#define IAxWinAmbientDispatchEx_get_BackColor(This,pclrBackground) (This)->lpVtbl->get_BackColor(This,pclrBackground)
#define IAxWinAmbientDispatchEx_put_ForeColor(This,clrForeground) (This)->lpVtbl->put_ForeColor(This,clrForeground)
#define IAxWinAmbientDispatchEx_get_ForeColor(This,pclrForeground) (This)->lpVtbl->get_ForeColor(This,pclrForeground)
#define IAxWinAmbientDispatchEx_put_LocaleID(This,lcidLocaleID) (This)->lpVtbl->put_LocaleID(This,lcidLocaleID)
#define IAxWinAmbientDispatchEx_get_LocaleID(This,plcidLocaleID) (This)->lpVtbl->get_LocaleID(This,plcidLocaleID)
#define IAxWinAmbientDispatchEx_put_UserMode(This,bUserMode) (This)->lpVtbl->put_UserMode(This,bUserMode)
#define IAxWinAmbientDispatchEx_get_UserMode(This,pbUserMode) (This)->lpVtbl->get_UserMode(This,pbUserMode)
#define IAxWinAmbientDispatchEx_put_DisplayAsDefault(This,bDisplayAsDefault) (This)->lpVtbl->put_DisplayAsDefault(This,bDisplayAsDefault)
#define IAxWinAmbientDispatchEx_get_DisplayAsDefault(This,pbDisplayAsDefault) (This)->lpVtbl->get_DisplayAsDefault(This,pbDisplayAsDefault)
#define IAxWinAmbientDispatchEx_put_Font(This,pFont) (This)->lpVtbl->put_Font(This,pFont)
#define IAxWinAmbientDispatchEx_get_Font(This,pFont) (This)->lpVtbl->get_Font(This,pFont)
#define IAxWinAmbientDispatchEx_put_MessageReflect(This,bMsgReflect) (This)->lpVtbl->put_MessageReflect(This,bMsgReflect)
#define IAxWinAmbientDispatchEx_get_MessageReflect(This,pbMsgReflect) (This)->lpVtbl->get_MessageReflect(This,pbMsgReflect)
#define IAxWinAmbientDispatchEx_get_ShowGrabHandles(This,pbShowGrabHandles) (This)->lpVtbl->get_ShowGrabHandles(This,pbShowGrabHandles)
#define IAxWinAmbientDispatchEx_get_ShowHatching(This,pbShowHatching) (This)->lpVtbl->get_ShowHatching(This,pbShowHatching)
#define IAxWinAmbientDispatchEx_put_DocHostFlags(This,dwDocHostFlags) (This)->lpVtbl->put_DocHostFlags(This,dwDocHostFlags)
#define IAxWinAmbientDispatchEx_get_DocHostFlags(This,pdwDocHostFlags) (This)->lpVtbl->get_DocHostFlags(This,pdwDocHostFlags)
#define IAxWinAmbientDispatchEx_put_DocHostDoubleClickFlags(This,dwDocHostDoubleClickFlags) (This)->lpVtbl->put_DocHostDoubleClickFlags(This,dwDocHostDoubleClickFlags)
#define IAxWinAmbientDispatchEx_get_DocHostDoubleClickFlags(This,pdwDocHostDoubleClickFlags) (This)->lpVtbl->get_DocHostDoubleClickFlags(This,pdwDocHostDoubleClickFlags)
#define IAxWinAmbientDispatchEx_put_AllowContextMenu(This,bAllowContextMenu) (This)->lpVtbl->put_AllowContextMenu(This,bAllowContextMenu)
#define IAxWinAmbientDispatchEx_get_AllowContextMenu(This,pbAllowContextMenu) (This)->lpVtbl->get_AllowContextMenu(This,pbAllowContextMenu)
#define IAxWinAmbientDispatchEx_put_AllowShowUI(This,bAllowShowUI) (This)->lpVtbl->put_AllowShowUI(This,bAllowShowUI)
#define IAxWinAmbientDispatchEx_get_AllowShowUI(This,pbAllowShowUI) (This)->lpVtbl->get_AllowShowUI(This,pbAllowShowUI)
#define IAxWinAmbientDispatchEx_put_OptionKeyPath(This,bstrOptionKeyPath) (This)->lpVtbl->put_OptionKeyPath(This,bstrOptionKeyPath)
#define IAxWinAmbientDispatchEx_get_OptionKeyPath(This,pbstrOptionKeyPath) (This)->lpVtbl->get_OptionKeyPath(This,pbstrOptionKeyPath)
/*** IAxWinAmbientDispatchEx methods ***/
#define IAxWinAmbientDispatchEx_SetAmbientDispatch(This,pDispatch) (This)->lpVtbl->SetAmbientDispatch(This,pDispatch)
#else
/*** IUnknown methods ***/
static inline HRESULT IAxWinAmbientDispatchEx_QueryInterface(IAxWinAmbientDispatchEx* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IAxWinAmbientDispatchEx_AddRef(IAxWinAmbientDispatchEx* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IAxWinAmbientDispatchEx_Release(IAxWinAmbientDispatchEx* This) {
    return This->lpVtbl->Release(This);
}
/*** IDispatch methods ***/
static inline HRESULT IAxWinAmbientDispatchEx_GetTypeInfoCount(IAxWinAmbientDispatchEx* This,UINT *pctinfo) {
    return This->lpVtbl->GetTypeInfoCount(This,pctinfo);
}
static inline HRESULT IAxWinAmbientDispatchEx_GetTypeInfo(IAxWinAmbientDispatchEx* This,UINT iTInfo,LCID lcid,ITypeInfo **ppTInfo) {
    return This->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo);
}
static inline HRESULT IAxWinAmbientDispatchEx_GetIDsOfNames(IAxWinAmbientDispatchEx* This,REFIID riid,LPOLESTR *rgszNames,UINT cNames,LCID lcid,DISPID *rgDispId) {
    return This->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId);
}
static inline HRESULT IAxWinAmbientDispatchEx_Invoke(IAxWinAmbientDispatchEx* This,DISPID dispIdMember,REFIID riid,LCID lcid,WORD wFlags,DISPPARAMS *pDispParams,VARIANT *pVarResult,EXCEPINFO *pExcepInfo,UINT *puArgErr) {
    return This->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr);
}
/*** IAxWinAmbientDispatch methods ***/
static inline HRESULT IAxWinAmbientDispatchEx_put_AllowWindowlessActivation(IAxWinAmbientDispatchEx* This,VARIANT_BOOL bCanWindowlessActivate) {
    return This->lpVtbl->put_AllowWindowlessActivation(This,bCanWindowlessActivate);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_AllowWindowlessActivation(IAxWinAmbientDispatchEx* This,VARIANT_BOOL *pbCanWindowlessActivate) {
    return This->lpVtbl->get_AllowWindowlessActivation(This,pbCanWindowlessActivate);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_BackColor(IAxWinAmbientDispatchEx* This,OLE_COLOR clrBackground) {
    return This->lpVtbl->put_BackColor(This,clrBackground);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_BackColor(IAxWinAmbientDispatchEx* This,OLE_COLOR *pclrBackground) {
    return This->lpVtbl->get_BackColor(This,pclrBackground);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_ForeColor(IAxWinAmbientDispatchEx* This,OLE_COLOR clrForeground) {
    return This->lpVtbl->put_ForeColor(This,clrForeground);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_ForeColor(IAxWinAmbientDispatchEx* This,OLE_COLOR *pclrForeground) {
    return This->lpVtbl->get_ForeColor(This,pclrForeground);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_LocaleID(IAxWinAmbientDispatchEx* This,LCID lcidLocaleID) {
    return This->lpVtbl->put_LocaleID(This,lcidLocaleID);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_LocaleID(IAxWinAmbientDispatchEx* This,LCID *plcidLocaleID) {
    return This->lpVtbl->get_LocaleID(This,plcidLocaleID);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_UserMode(IAxWinAmbientDispatchEx* This,VARIANT_BOOL bUserMode) {
    return This->lpVtbl->put_UserMode(This,bUserMode);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_UserMode(IAxWinAmbientDispatchEx* This,VARIANT_BOOL *pbUserMode) {
    return This->lpVtbl->get_UserMode(This,pbUserMode);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_DisplayAsDefault(IAxWinAmbientDispatchEx* This,VARIANT_BOOL bDisplayAsDefault) {
    return This->lpVtbl->put_DisplayAsDefault(This,bDisplayAsDefault);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_DisplayAsDefault(IAxWinAmbientDispatchEx* This,VARIANT_BOOL *pbDisplayAsDefault) {
    return This->lpVtbl->get_DisplayAsDefault(This,pbDisplayAsDefault);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_Font(IAxWinAmbientDispatchEx* This,IFontDisp *pFont) {
    return This->lpVtbl->put_Font(This,pFont);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_Font(IAxWinAmbientDispatchEx* This,IFontDisp **pFont) {
    return This->lpVtbl->get_Font(This,pFont);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_MessageReflect(IAxWinAmbientDispatchEx* This,VARIANT_BOOL bMsgReflect) {
    return This->lpVtbl->put_MessageReflect(This,bMsgReflect);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_MessageReflect(IAxWinAmbientDispatchEx* This,VARIANT_BOOL *pbMsgReflect) {
    return This->lpVtbl->get_MessageReflect(This,pbMsgReflect);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_ShowGrabHandles(IAxWinAmbientDispatchEx* This,VARIANT_BOOL *pbShowGrabHandles) {
    return This->lpVtbl->get_ShowGrabHandles(This,pbShowGrabHandles);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_ShowHatching(IAxWinAmbientDispatchEx* This,VARIANT_BOOL *pbShowHatching) {
    return This->lpVtbl->get_ShowHatching(This,pbShowHatching);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_DocHostFlags(IAxWinAmbientDispatchEx* This,DWORD dwDocHostFlags) {
    return This->lpVtbl->put_DocHostFlags(This,dwDocHostFlags);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_DocHostFlags(IAxWinAmbientDispatchEx* This,DWORD *pdwDocHostFlags) {
    return This->lpVtbl->get_DocHostFlags(This,pdwDocHostFlags);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_DocHostDoubleClickFlags(IAxWinAmbientDispatchEx* This,DWORD dwDocHostDoubleClickFlags) {
    return This->lpVtbl->put_DocHostDoubleClickFlags(This,dwDocHostDoubleClickFlags);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_DocHostDoubleClickFlags(IAxWinAmbientDispatchEx* This,DWORD *pdwDocHostDoubleClickFlags) {
    return This->lpVtbl->get_DocHostDoubleClickFlags(This,pdwDocHostDoubleClickFlags);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_AllowContextMenu(IAxWinAmbientDispatchEx* This,VARIANT_BOOL bAllowContextMenu) {
    return This->lpVtbl->put_AllowContextMenu(This,bAllowContextMenu);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_AllowContextMenu(IAxWinAmbientDispatchEx* This,VARIANT_BOOL *pbAllowContextMenu) {
    return This->lpVtbl->get_AllowContextMenu(This,pbAllowContextMenu);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_AllowShowUI(IAxWinAmbientDispatchEx* This,VARIANT_BOOL bAllowShowUI) {
    return This->lpVtbl->put_AllowShowUI(This,bAllowShowUI);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_AllowShowUI(IAxWinAmbientDispatchEx* This,VARIANT_BOOL *pbAllowShowUI) {
    return This->lpVtbl->get_AllowShowUI(This,pbAllowShowUI);
}
static inline HRESULT IAxWinAmbientDispatchEx_put_OptionKeyPath(IAxWinAmbientDispatchEx* This,BSTR bstrOptionKeyPath) {
    return This->lpVtbl->put_OptionKeyPath(This,bstrOptionKeyPath);
}
static inline HRESULT IAxWinAmbientDispatchEx_get_OptionKeyPath(IAxWinAmbientDispatchEx* This,BSTR *pbstrOptionKeyPath) {
    return This->lpVtbl->get_OptionKeyPath(This,pbstrOptionKeyPath);
}
/*** IAxWinAmbientDispatchEx methods ***/
static inline HRESULT IAxWinAmbientDispatchEx_SetAmbientDispatch(IAxWinAmbientDispatchEx* This,IDispatch *pDispatch) {
    return This->lpVtbl->SetAmbientDispatch(This,pDispatch);
}
#endif
#endif

#endif


#endif  /* __IAxWinAmbientDispatchEx_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IInternalConnection interface
 */
#ifndef __IInternalConnection_INTERFACE_DEFINED__
#define __IInternalConnection_INTERFACE_DEFINED__

DEFINE_GUID(IID_IInternalConnection, 0x72ad0770, 0x6a9f, 0x11d1, 0xbc,0xec, 0x00,0x60,0x08,0x8f,0x44,0x4e);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("72ad0770-6a9f-11d1-bcec-0060088f444e")
IInternalConnection : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE AddConnection(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE ReleaseConnection(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IInternalConnection, 0x72ad0770, 0x6a9f, 0x11d1, 0xbc,0xec, 0x00,0x60,0x08,0x8f,0x44,0x4e)
#endif
#else
typedef struct IInternalConnectionVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IInternalConnection *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IInternalConnection *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IInternalConnection *This);

    /*** IInternalConnection methods ***/
    HRESULT (STDMETHODCALLTYPE *AddConnection)(
        IInternalConnection *This);

    HRESULT (STDMETHODCALLTYPE *ReleaseConnection)(
        IInternalConnection *This);

    END_INTERFACE
} IInternalConnectionVtbl;

interface IInternalConnection {
    CONST_VTBL IInternalConnectionVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IInternalConnection_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IInternalConnection_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IInternalConnection_Release(This) (This)->lpVtbl->Release(This)
/*** IInternalConnection methods ***/
#define IInternalConnection_AddConnection(This) (This)->lpVtbl->AddConnection(This)
#define IInternalConnection_ReleaseConnection(This) (This)->lpVtbl->ReleaseConnection(This)
#else
/*** IUnknown methods ***/
static inline HRESULT IInternalConnection_QueryInterface(IInternalConnection* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IInternalConnection_AddRef(IInternalConnection* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IInternalConnection_Release(IInternalConnection* This) {
    return This->lpVtbl->Release(This);
}
/*** IInternalConnection methods ***/
static inline HRESULT IInternalConnection_AddConnection(IInternalConnection* This) {
    return This->lpVtbl->AddConnection(This);
}
static inline HRESULT IInternalConnection_ReleaseConnection(IInternalConnection* This) {
    return This->lpVtbl->ReleaseConnection(This);
}
#endif
#endif

#endif


#endif  /* __IInternalConnection_INTERFACE_DEFINED__ */

namespace ATL
{
#ifdef __cplusplus
#include <atldef.h>
#else
#define ATLAPI EXTERN_C HRESULT __declspec(dllimport) __stdcall
#define ATLAPI_(x) EXTERN_C __declspec(dllimport) x __stdcall
#define ATLINLINE
#endif	// __cplusplus

ATLAPI_(INT_PTR) AtlAxDialogBoxW(HINSTANCE hInstance, LPCWSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogProc, LPARAM dwInitParam);
ATLAPI_(INT_PTR) AtlAxDialogBoxA(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogProc, LPARAM dwInitParam);
#ifdef UNICODE
#define AtlAxDialogBox AtlAxDialogBoxW
#else
#define AtlAxDialogBox AtlAxDialogBoxA
#endif

ATLAPI_(HWND) AtlAxCreateDialogW(HINSTANCE hInstance, LPCWSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogProc, LPARAM dwInitParam);
ATLAPI_(HWND) AtlAxCreateDialogA(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogProc, LPARAM dwInitParam);
#ifdef UNICODE
#define AtlAxCreateDialog AtlAxCreateDialogW
#else
#define AtlAxCreateDialog AtlAxCreateDialogA
#endif

ATLAPI AtlAxCreateControl(LPCOLESTR lpszName, HWND hWnd, IStream* pStream, IUnknown** ppUnkContainer);
#ifdef __cplusplus
ATLAPI AtlAxCreateControlEx(LPCOLESTR lpszName, HWND hWnd, IStream* pStream, 
		IUnknown** ppUnkContainer, IUnknown** ppUnkControl, 
		REFIID iidSink=IID_NULL, IUnknown* punkSink=NULL);
ATLAPI AtlAxCreateControlLic(LPCOLESTR lpszName, HWND hWnd, IStream* pStream, IUnknown** ppUnkContainer, BSTR bstrLic = NULL);
ATLAPI AtlAxCreateControlLicEx(LPCOLESTR lpszName, HWND hWnd, IStream* pStream, 
		IUnknown** ppUnkContainer, IUnknown** ppUnkControl, 
		REFIID iidSink=IID_NULL, IUnknown* punkSink=NULL, BSTR bstrLic = NULL);
#else
ATLAPI AtlAxCreateControlEx(LPCOLESTR lpszName, HWND hWnd, IStream* pStream, 
		IUnknown** ppUnkContainer, IUnknown** ppUnkControl, 
		REFIID iidSink, IUnknown* punkSink);
ATLAPI AtlAxCreateControlLic(LPCOLESTR lpszName, HWND hWnd, IStream* pStream, IUnknown** ppUnkContainer, BSTR bstrLic);
ATLAPI AtlAxCreateControlLicEx(LPCOLESTR lpszName, HWND hWnd, IStream* pStream, 
		IUnknown** ppUnkContainer, IUnknown** ppUnkControl, 
		REFIID iidSink, IUnknown* punkSink, BSTR bstrLic);
#endif	// __cplusplus
ATLAPI AtlAxAttachControl(IUnknown* pControl, HWND hWnd, IUnknown** ppUnkContainer);
ATLAPI_(BOOL) AtlAxWinInit();

ATLAPI AtlAxGetHost(HWND h, IUnknown** pp);
ATLAPI AtlAxGetControl(HWND h, IUnknown** pp);

}; //namespace ATL
#ifndef __IAccessibleServer_FWD_DEFINED__
#define __IAccessibleServer_FWD_DEFINED__
typedef interface IAccessibleServer IAccessibleServer;
#ifdef __cplusplus
interface IAccessibleServer;
#endif /* __cplusplus */
#endif

/*****************************************************************************
 * IAccessibleProxy interface
 */
#ifndef __IAccessibleProxy_INTERFACE_DEFINED__
#define __IAccessibleProxy_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAccessibleProxy, 0x7a7d9dcf, 0xb7a1, 0x4019, 0x90,0x31, 0x25,0x82,0x68,0x84,0x69,0x80);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("7a7d9dcf-b7a1-4019-9031-258268846980")
IAccessibleProxy : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE SetServer(
        IAccessible *pAccessible,
        IAccessibleServer *pServer) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAccessibleProxy, 0x7a7d9dcf, 0xb7a1, 0x4019, 0x90,0x31, 0x25,0x82,0x68,0x84,0x69,0x80)
#endif
#else
typedef struct IAccessibleProxyVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAccessibleProxy *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAccessibleProxy *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAccessibleProxy *This);

    /*** IAccessibleProxy methods ***/
    HRESULT (STDMETHODCALLTYPE *SetServer)(
        IAccessibleProxy *This,
        IAccessible *pAccessible,
        IAccessibleServer *pServer);

    END_INTERFACE
} IAccessibleProxyVtbl;

interface IAccessibleProxy {
    CONST_VTBL IAccessibleProxyVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAccessibleProxy_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAccessibleProxy_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAccessibleProxy_Release(This) (This)->lpVtbl->Release(This)
/*** IAccessibleProxy methods ***/
#define IAccessibleProxy_SetServer(This,pAccessible,pServer) (This)->lpVtbl->SetServer(This,pAccessible,pServer)
#else
/*** IUnknown methods ***/
static inline HRESULT IAccessibleProxy_QueryInterface(IAccessibleProxy* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IAccessibleProxy_AddRef(IAccessibleProxy* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IAccessibleProxy_Release(IAccessibleProxy* This) {
    return This->lpVtbl->Release(This);
}
/*** IAccessibleProxy methods ***/
static inline HRESULT IAccessibleProxy_SetServer(IAccessibleProxy* This,IAccessible *pAccessible,IAccessibleServer *pServer) {
    return This->lpVtbl->SetServer(This,pAccessible,pServer);
}
#endif
#endif

#endif


#endif  /* __IAccessibleProxy_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAccessibleServer interface
 */
#ifndef __IAccessibleServer_INTERFACE_DEFINED__
#define __IAccessibleServer_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAccessibleServer, 0x52c8fb5e, 0xd779, 0x4e77, 0xae,0x9f, 0xf6,0x11,0xfa,0x7e,0x9d,0x7a);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("52c8fb5e-d779-4e77-ae9f-f611fa7e9d7a")
IAccessibleServer : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE SetProxy(
        IAccessibleProxy *pUnknown) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetHWND(
        HWND *phWnd) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetEnumVariant(
        IEnumVARIANT **ppEnumVariant) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAccessibleServer, 0x52c8fb5e, 0xd779, 0x4e77, 0xae,0x9f, 0xf6,0x11,0xfa,0x7e,0x9d,0x7a)
#endif
#else
typedef struct IAccessibleServerVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAccessibleServer *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAccessibleServer *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAccessibleServer *This);

    /*** IAccessibleServer methods ***/
    HRESULT (STDMETHODCALLTYPE *SetProxy)(
        IAccessibleServer *This,
        IAccessibleProxy *pUnknown);

    HRESULT (STDMETHODCALLTYPE *GetHWND)(
        IAccessibleServer *This,
        HWND *phWnd);

    HRESULT (STDMETHODCALLTYPE *GetEnumVariant)(
        IAccessibleServer *This,
        IEnumVARIANT **ppEnumVariant);

    END_INTERFACE
} IAccessibleServerVtbl;

interface IAccessibleServer {
    CONST_VTBL IAccessibleServerVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAccessibleServer_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAccessibleServer_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAccessibleServer_Release(This) (This)->lpVtbl->Release(This)
/*** IAccessibleServer methods ***/
#define IAccessibleServer_SetProxy(This,pUnknown) (This)->lpVtbl->SetProxy(This,pUnknown)
#define IAccessibleServer_GetHWND(This,phWnd) (This)->lpVtbl->GetHWND(This,phWnd)
#define IAccessibleServer_GetEnumVariant(This,ppEnumVariant) (This)->lpVtbl->GetEnumVariant(This,ppEnumVariant)
#else
/*** IUnknown methods ***/
static inline HRESULT IAccessibleServer_QueryInterface(IAccessibleServer* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IAccessibleServer_AddRef(IAccessibleServer* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IAccessibleServer_Release(IAccessibleServer* This) {
    return This->lpVtbl->Release(This);
}
/*** IAccessibleServer methods ***/
static inline HRESULT IAccessibleServer_SetProxy(IAccessibleServer* This,IAccessibleProxy *pUnknown) {
    return This->lpVtbl->SetProxy(This,pUnknown);
}
static inline HRESULT IAccessibleServer_GetHWND(IAccessibleServer* This,HWND *phWnd) {
    return This->lpVtbl->GetHWND(This,phWnd);
}
static inline HRESULT IAccessibleServer_GetEnumVariant(IAccessibleServer* This,IEnumVARIANT **ppEnumVariant) {
    return This->lpVtbl->GetEnumVariant(This,ppEnumVariant);
}
#endif
#endif

#endif


#endif  /* __IAccessibleServer_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER HWND_UserSize     (ULONG *, ULONG, HWND *);
unsigned char * __RPC_USER HWND_UserMarshal  (ULONG *, unsigned char *, HWND *);
unsigned char * __RPC_USER HWND_UserUnmarshal(ULONG *, unsigned char *, HWND *);
void            __RPC_USER HWND_UserFree     (ULONG *, HWND *);
ULONG           __RPC_USER BSTR_UserSize     (ULONG *, ULONG, BSTR *);
unsigned char * __RPC_USER BSTR_UserMarshal  (ULONG *, unsigned char *, BSTR *);
unsigned char * __RPC_USER BSTR_UserUnmarshal(ULONG *, unsigned char *, BSTR *);
void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);

/* End additional prototypes */

#endif /* __atliface_h__ */
