/*** Autogenerated by WIDL 10.10 - Do not edit ***/

#define PROXY_DELEGATION
#include <objbase.h>
#include <rpcproxy.h>

#ifdef __cplusplus
extern "C" {
#endif

EXTERN_PROXY_FILE(atliface)

PROXYFILE_LIST_START
/* Start of list */
  REFERENCE_PROXY_FILE(atliface),
/* End of list */
PROXYFILE_LIST_END

DLLDATA_ROUTINES(aProxyFileList, GET_DLL_CLSID)

#ifdef __cplusplus
}
#endif

