TARGETNAME=freecell
TARGETPATH=../../bin
TARGETTYPE=APPLICATION
CC = aarch64-pc-mingw32-gcc
CXX = aarch64-pc-mingw32-g++
AR = aarch64-pc-mingw32-ar
WINDRES = aarch64-pc-mingw32-windres -D_UNICODE=1 -DUNICODE=1
RANLIB = aarch64-pc-mingw32-ranlib
CFLAGS = -O2 -I. -Wall -Wpedantic -D_UNICODE=1 -DUNICODE=1 -D__STDC_WANT_SECURE_LIB__=1
LDFLAGS = -static-libgcc -mwindows
LIBS = -lgdi32 -lhtmlhelp -lwinmm -lcomctl32
RM = rm -f
INSTALL = install -m 755
INSTALL_DIR = /usr

OBJS = \
	cards.o \
	cards_res.o \
	dialog.o \
	display.o \
	freecell.o \
	freecell_res.o \
	game.o \
	game2.o \
	glide.o \
	transfer.o

%_res.o: %.rc
	$(WINDRES) -o $@ $<

%.o: %.c
	$(CC) $(CFLAGS) -DLIB_EXPORTS=1 -o $@ -c $<

all: $(TARGETNAME).exe

$(TARGETNAME).exe: $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	$(RM) $(OBJS) $(DLL_OBJS) $(TARGETNAME).exe

install:
	$(INSTALL) $(TARGETNAME).exe $(INSTALL_DIR)/bin/$(TARGETNAME).exe

